### ISSUE TITLE
Webhooks permission

### ISSUE THREAD

**Issue by simonklb** [Half-Shot/matrix-appservice-discord#11]
Manage webhooks permission seem to be needed for the Discord bot to work properly (please verify). If that's really the case, just need to add the `MANAGE_WEBHOOKS` flag to addbot.ts

**Comment by ollieh** [comment]
Yes that's correct, I've added this change into #10. I guess it would also be good if the bot created the webhooks if they didn't exist.

**Comment by Half-Shot** [comment]
Added in 9ffd6eab533fe9526380c2a68366611ed5b097d6
