### ISSUE TITLE
Forward m.sticker events to discord

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#110]

**Comment by Half-Shot** [comment]
@turt2live is there a spec I can poke at?

**Comment by turt2live** [comment]
@Half-Shot here's the current spec: https://matrix.org/docs/spec/client_server/unstable.html#sticker-messages

**Comment by Half-Shot** [comment]
This has been fixed by #120. I'll worry about any changes to stickers in a new issue.
