### ISSUE TITLE
/me is inconsistent

### ISSUE THREAD

**Issue by ZerataX** [Half-Shot/matrix-appservice-discord#112]
if John uses `/me`, the resulting message on matrix will look like this:
`*John slaps Jim around a bit with a large trout `
while on discord it looks like this:
`slaps Jim around a bit with a large trout `

**Comment by Half-Shot** [comment]
Yeah, discord messes up /me and transforms it into italics :/. Not much we can do.

**Comment by Half-Shot** [comment]
https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/31038886--me-irc-like

**Comment by Half-Shot** [comment]
Ah, that's because we try to mock the result that we see on discord for /me. Which is bad and wrong, and I'd be minded to copy Riot on this occasion.

**Comment by Half-Shot** [comment]
Removing upstream since the ball is kinda in our court with this one.

**Comment by Sorunome** [comment]
fixed in #244
