### ISSUE TITLE
discord bot messages should use m.notice

### ISSUE THREAD

**Issue by ZerataX** [Half-Shot/matrix-appservice-discord#113]
If a message by discord bot gets bridged over to matrix it should probably also be of the message type `m.notice`

at least that's how I understand currently bots on matrix are supposed to send messages.

**Comment by Half-Shot** [comment]
Don't think there is any strict requirements on it, though yeah I suppose that makes sense. Would definitely format a bit nicer.

**Comment by Sorunome** [comment]
got implemented
