### ISSUE TITLE
Add support for inline images

### ISSUE THREAD

**Issue by TildeSlashC0re** [Half-Shot/matrix-appservice-discord#117]
Inline images are currently only represented by a string that says `Inline Image`. 

> You know I totally forgot inline images are a thing.
> - HalfShot

:smile:

**Comment by TildeSlashC0re** [comment]
since the scope of the operations I'm aiming for is highly dependent on this feature I'm providing a $50 bounty (at the time of implementation) in a cryptocurrency of your choice.

You can contact me `@c0re:0xbtfd.one` if you want to claim it.

**Comment by Sorunome** [comment]
merged
