### ISSUE TITLE
mentions don't work for nonascii characters

### ISSUE THREAD

**Issue by ZerataX** [Half-Shot/matrix-appservice-discord#118]
it is currently impossible to mention a discord user where the nickname ends or starts with a non-ascii character.

this is because javascript doesn't support unicode properly for word boundaries `\b`
as used here:
```typescript
new RegExp(
  `\\b(${matcher})(?=\\b)`
  , "mig"), `<@!${member.id}>`,
);
```
https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/src/matrixeventprocessor.ts#L87

and this behavior will apparently also not change with the `/u` flag:
https://github.com/mathiasbynens/es-regexp-unicode-character-class-escapes/issues/1#issuecomment-62251775

so something like this could work
```js
/(?<=\W|^)(${matcher})(?=\W|$)/igmu
```
not using \w since that doesn't support astral characters?
but idk I'm not too familiar with typescript so you'd probably have to transpile it to something compliant with es5 and of course think around the lookbehind.

**Comment by Half-Shot** [comment]
I found there were a few issues with using ``\W|^`` so I've gone with:

```javascript
const WORD_BOUNDARY = "(^|\:|\@|\#|```|\\s|$|,)";
const regex = new RegExp(`(?<=${WORD_BOUNDARY})(${matcher})(?=${WORD_BOUNDARY})`, "igmu");

Which works so long as you don't mind dropping <9.X compatibility, which bothers me. The lookbehind feature is new.

**Comment by Half-Shot** [comment]
Merged. Please re-open if this is still affecting you @ZerataX

**Comment by ZerataX** [comment]
works great, too bad lookbehind is this new. thanks!
