### ISSUE TITLE
Refactor code for 0.3.0

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#126]
The code base has got rather gnarly over the year or so it's been worked on and while the linter has stopped this to a certain extent, there are several areas I'd like to improve to make it easier to work on.

Here are some goals I have in mind for 0.3.0, please comment if you think I've missed anything or these are bad ideas:

 - [x] Use 4 spaces for indent, rather than the horrible mix we have.
 - [ ] Trim down bot.ts to 400 lines, move code to handler classes.
 - [ ] Decide and explicitly state a convention for function names such as handler/public/private.
-  [ ] Improve test coverage so that we can stomp out more bugs

**Comment by Sorunome** [comment]
see #270 for part of it

**Comment by Sorunome** [comment]
@Half-Shot what's left?

**Comment by Half-Shot** [comment]
Honestly, I'd be happy to close this. We managed to lint all the things.
