### ISSUE TITLE
Media redactions don't bridge from Discord -> Matrix properly

### ISSUE THREAD

**Issue by eeeeeta** [Half-Shot/matrix-appservice-discord#146]
> current upstream develop has a bug wherein it doesn't store, e.g. m.image events (like attachments) in the message store, so redactions of that media from discord don't go through correctly [[message link]](https://matrix.to/#/!qPNOnUsNsZrToFZqxB:half-shot.uk/$1527622355987hUSCZ:theta.eu.org)

example fix: https://github.com/eeeeeta/matrix-appservice-discord/commit/97ae1b36df263dabb22033206a21d2b6444e2d24

**Comment by eeeeeta** [comment]
actually, huh, you could probably literally cherry-pick that into a PR, hang on

**Comment by Half-Shot** [comment]
Merged. Closing
