### ISSUE TITLE
Add bot commands to kick/ban Matrix users on Discord

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#156]
Something to take into account here is ownership:
- It would be safe to kick/ban users on a "portal" (created from an alias request)
- It's a little trickier with plumbed rooms as the discord bridge can't assume ownership.

Also powerlevels:
- Who should be allowed to ban people on Discord? Can we allow anyone with a certain role on Discord to ban Matrix users or should we somehow detect their powerlevel on Matrix?

**Comment by Half-Shot** [comment]
This is being done in #210

**Comment by Sorunome** [comment]
this is merged
