### ISSUE TITLE
Support PostgreSQL as an option

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#158]
The bridge I run is approaching capacity at 22k+ active users due to the bridge not being able to acquire locks on the database fast enough. At the very least, switching to postgres would alleviate some of the concern, even without optimizing the code for it.

**Comment by Half-Shot** [comment]
Could we start batching together event writes, as a stopgap until I can look into options? That and/or caching?

**Comment by turt2live** [comment]
It's already trying to write a continuous stream of events to the database. It might be best to take the plunge into postgres :(

I'll set aside some time to at least try to do the migration.

**Comment by Half-Shot** [comment]
So how I'd attack this would be to make ``DiscordStore`` use an interface, and then split it out to a sqlite class or a postgres class.

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-appservice-discord/pull/251 moves the sqlite-y bits to it's own connector, so adding rudimentary postgres support should be trivial.

**Comment by Half-Shot** [comment]
This can be closed.
