### ISSUE TITLE
Filter out rogue HTML from messages

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#163]
@tulir has created pretty rainbox text using ``<font>`` and in the process made discord look super ugly.

**Comment by Sorunome** [comment]
I think that the issue is that, in the normal `body` attribute that html is, not only in `formatted_body` when sending stuff.

**Comment by Half-Shot** [comment]
Yes, that certainly doesn't help.

**Comment by Sorunome** [comment]
merged
