### ISSUE TITLE
Log when messages are (not) going through to the other side

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#17]
It's hard to troubleshoot when the logs are quiet. Log when messages come from matrix and get sent to discord and the other way around. Preferably with the room/alias

**Comment by Half-Shot** [comment]
I might be being thick, but whereabouts am I missing logging for this?

**Comment by turt2live** [comment]
It looks like it's been added since reporting. Closing as "probably fixed". 

(I also don't remember why I wanted this, and it probably wasn't even a bridge problem).
