### ISSUE TITLE
 WARN PresenceHandler Could not update Matrix presence for <RANDOM 18-DIGIT Number>

### ISSUE THREAD

**Issue by redsolver** [Half-Shot/matrix-appservice-discord#172]
When I start the matrix-appservice-discord,
I get one of this per second:
 WARN PresenceHandler Could not update Matrix presence for <RANDOM 18-DIGIT Number>

**Comment by Half-Shot** [comment]
Probably because we are trying to update presence on discord who don't exist,on matrix yet since the user has not spoken. You can safely ignore these errors.
