### ISSUE TITLE
Add extra information keys to m.room.member events for members

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#173]
/dev/ponies has nefarious use cases for this, such as colouring users in their fork of Riot. We should support putting in discord keys into the body such as: 

``com.discordapp.member.rolecolour``
``com.discordapp.member.bot``

**Comment by anoadragon453** [comment]
![](http://static.comicvine.com/uploads/original/14/144443/4509795-3444595_640px.jpg)

I am on the case.

**Comment by Half-Shot** [comment]
I fear for the project

**Comment by Sorunome** [comment]
got implemented
