### ISSUE TITLE
Strikethrough doesn't bridge correctly

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#176]
Typing `<del>hi</del>` causes strikethrough in Riot, but Discord users just see the HTML tags.

**Comment by Half-Shot** [comment]
We don't do HTML parsing for the discord bridge, only Markdown. I believe we support ``~~text~~`` which is correct.

**Comment by anoadragon453** [comment]
Ah, but Riot doesn't support that. Maybe that's the real bug? :P

**Comment by Half-Shot** [comment]
Just checked, Commonmark doesn't support it but GHFM does. I suspect Riot shouldn't be doing that.

**Comment by Half-Shot** [comment]
Though arguably, we should be parsing the html back into markdown possibly so we aren't dependant on versions.

**Comment by Half-Shot** [comment]
#186 has been merged so closing
