### ISSUE TITLE
Can't join rooms on matrix

### ISSUE THREAD

**Issue by Bitti09** [Half-Shot/matrix-appservice-discord#2]
Discord side works (bot is  online and recives  presence  changes from discord) 
but i can't join the rooms on my local  matrix server.

Bot log shows:
GET //rooms/%23_discord_22497740072xxxxxx_22497817263xxxxx%3Axxxxxx.de?access_token=<REDACTED> HTTP/1.1" 404 160 "-" "Synapse/0.19.2"

**Comment by aaronraimist** [comment]
If you aren't already running the develop branch you probably should switch to that. Also try adding 

```
logging:
  level: verbose
```

**Comment by Bitti09** [comment]
Already done.

Bot Log starts with 

info discordas Starting Discord AS
info discordas Initing bridge.
info AppServ Started listening on port 9005 at Fri, 24 Feb 2017 18:32:31 GMT
info discordas Initing store.
info DiscordStore Starting DB Init
info DiscordStore Updated database to the latest schema
info discordas Initing bot.
info DiscordBot Updating presence for xxxx
and loops "{"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}
" for every  presence change after that lines

**Comment by Bitti09** [comment]
Update:
for some reasone it works now after following change:
in file discord-registration.yaml

url: 'http://localhost:9005/' ->  url: 'http://localhost:9005'

the / after the port number seems to be the reason.
cause now it generates vaild url like "http://localhost:9005/rooms/%23_discord_:" instead of "http://localhost:9005//rooms/%23_discord_:"

**Comment by aaronraimist** [comment]
Oh right, yes this is a known bug that should be fixed soon. I think the only change that needs to get made is in the README. I opened a pull request.

**Comment by Half-Shot** [comment]
Going to close as it's not really something I have control over :/
