### ISSUE TITLE
Cannot run admin tools (getbotlink, adminme) from Docker image

### ISSUE THREAD

**Issue by Pneumaticat** [Half-Shot/matrix-appservice-discord#205]
The Docker image doesn't have package.json, which is necessary for npm, nor does it have any of the JavaScript files from the tools/ directory, so you can't run `npm run-script getbotlink` or `npm run-script adminme` as described in the docs.

**Comment by Half-Shot** [comment]
@turt2live ?

**Comment by adrianmalacoda** [comment]
You should be able to run the tools directly through `node`, i.e. as `node ./build/tools/adminme.js`. The Dockerfile should perhaps put these tools on the PATH though to make them more convenient to use (e.g. `docker exec $container_name adminme`.

So far as I can tell the Docker image contains `build` which is where the *executable* form of the tools resides (`tools` is a TypeScript source code directory)

**Comment by turt2live** [comment]
This seems to be one of the cases that I simply forgot about when contributing the docker image in the first place. Personally I use different tooling to do the tasks that the scripts provide, and forgot that they existed in the project :(

although, I do seem to have forced the container to ignore the folder for some reason: https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/.dockerignore#L15

**Comment by Half-Shot** [comment]
#208 has been merged, closing.
