### ISSUE TITLE
Discord-ping needs better checking

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#21]
![image](https://user-images.githubusercontent.com/1190097/28438167-71f8600c-6d5a-11e7-9f83-d8a350d5b68e.png)

**Comment by turt2live** [comment]
This is even worse for some people:
![image](https://user-images.githubusercontent.com/1190097/28471904-e7b19088-6dfb-11e7-8c91-b9b5d6f1fc54.png)

**Comment by jcgruenhage** [comment]
maybe only make a ping when there is an @ before that? it's not the matrix way, but it would fix this.

**Comment by turt2live** [comment]
The matrix solution would probably be less eager regex. If the text is the start of the string and has word boundaries, then ping.

**Comment by turt2live** [comment]
> basically if it's a link with a matrix.to (or eventually a mx://), it's a mention

**Comment by jcgruenhage** [comment]
We could use the matrix mentions to fix this.. although it would require other bridges to implement this too, to be of most use.

**Comment by POPCORNS1068** [comment]
![captu2re](https://user-images.githubusercontent.com/30457182/30036344-0e384f3c-91e5-11e7-968e-368a9c3d6d56.PNG)

**Comment by Half-Shot** [comment]
Discussion on the issue is now in #32
