### ISSUE TITLE
Changing avatar or username joins user

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#219]
If there is a room in a guild (discord side) that a user can't view (due to e.g. roles) if they change their username or their avatar their ghost will still be joined to the matrix-side room.

**Comment by Half-Shot** [comment]
I suspect the user synchroniser fetches all channels in the guild and joins all of the users. We should be able to fix this by first checking channel by channel for guild state changes and then adding in code to leave them from rooms they no longer have permission to view.

**Comment by Sorunome** [comment]
Yep, I was waiting on #194 first before addressing this

**Comment by Sorunome** [comment]
merged

**Comment by Sorunome** [comment]
merged
