### ISSUE TITLE
Missing Arms

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#222]
Arms get lost when sending from discord to matrix! Help the arms!

Discord:

![screenshot_2018-08-06_21-11-05](https://user-images.githubusercontent.com/2433620/43736300-671f2b44-99bd-11e8-9faf-123468387127.png)

Matrix:

![screenshot_2018-08-06_21-12-34](https://user-images.githubusercontent.com/2433620/43736325-7a22cb9c-99bd-11e8-964c-ffe4240459d4.png)

**Comment by Half-Shot** [comment]
Oh no. Not the arms!

We should probably escape the arms

**Comment by Sorunome** [comment]
problem is that discord uses \\ only for escaping known markdown key-chars, but marked.js just gobbles up all the \\

**Comment by turt2live** [comment]
Resurgence of https://github.com/Half-Shot/matrix-appservice-discord/issues/67 (should probably have a test for this)

**Comment by Sorunome** [comment]
it turns out discord special-cases this exact emote so that in that specific case \ doesn't escape (discord side):

`¯\_(ツ)_/¯` -> not dropped
`¯\_(ツ)_/` -> dropped
`\_(ツ)_/¯` -> dropped
`¯\_(a)_/¯` -> dropped

**Comment by Sorunome** [comment]
fixed
