### ISSUE TITLE
Proxy embeds to Matrix

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#23]
Many other Discord bots use embeds to communicate what is going on. It would be nice to see these in Matrix, at least at a rudimentary level.

iirc, embeds are also used for quoting other users.

**Comment by Half-Shot** [comment]
This has been started by 823392e6100eab802152a04f4b143dfc2235793a which will process the basic elements of an embed.

**Comment by Half-Shot** [comment]
I'm going to close this since we support the basic elements now, and extending this can be in future issues,
