### ISSUE TITLE
We fail to send messages if we cannot get the state of the sender's member event

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#236]
We should be ignoring this and doing a profile lookup

**Comment by Sorunome** [comment]
Is this still the case? Pretty sure it was fixed at some point down the road

**Comment by Sorunome** [comment]
Yep, it was fixed: https://github.com/Half-Shot/matrix-appservice-discord/blob/fea9ca8263c16929414a352318007f38248d3bb0/src/matrixeventprocessor.ts#L206
