### ISSUE TITLE
@everyone and @here mentions ignore permissions and config

### ISSUE THREAD

**Issue by Teteros** [Half-Shot/matrix-appservice-discord#237]
![ss](https://user-images.githubusercontent.com/5067989/44924507-6729b200-ad43-11e8-8506-02f082222b21.png)

Typing `@here` or `@everyone` directly on matrix will ping everyone who can read the channel on discord.

Those pings work even with "Mention Everyone" bot permissions **off**:
![ss](https://user-images.githubusercontent.com/5067989/44924588-a6f09980-ad43-11e8-9a86-a34fd50f2c47.png)

and ignore the value of `disableDiscordMentions` in `config.yaml`
(` disableDiscordMentions: true` was set)

This means there is no way to suppress pings coming from matrix users on Discord's side which can be abused.

**Comment by Half-Shot** [comment]
You can actually set ``disableEveryoneMention`` and ``disableHereMention`` in the config but it's not documented anywhere :|

**EDIT**: These are not plural

**Comment by Half-Shot** [comment]
Now it is.
