### ISSUE TITLE
Usernames not parsed in Message Replies

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#238]
![image](https://user-images.githubusercontent.com/1342360/45096866-5f1c9a00-b0d6-11e8-9201-3a332dc14d7b.png)

Usernames are not parsed into Discord compatible usernames in replies properly. Here is another example.

![del1](https://user-images.githubusercontent.com/1342360/45096950-925f2900-b0d6-11e8-8c3c-2c8e0d448cd9.png)
![del1](https://user-images.githubusercontent.com/1342360/45096964-9e4aeb00-b0d6-11e8-8e78-2b90d22d7b2c.png)

Not sure if it's due to the `>` in front or the bot not parsing correctly.

**Comment by Sorunome** [comment]
It is because that is exactly how the markdown for the replies looks like. I agree that it needs better displaying on the discord side

**Comment by Sorunome** [comment]
done in  #259
