### ISSUE TITLE
3pid fails to create and join rooms

### ISSUE THREAD

**Issue by bluesaxman** [Half-Shot/matrix-appservice-discord#241]
Tested in Riot 0.16.3
3pid integration does show up in the drop down menu, however when selecting it and trying to join a room, you are presented with "Room does not exist" This only happens when you try to connect using this method. It will work fine if you select your homeserver from the list and then present it with the exact same join request, or use the join command. Its only when you have the guild selected in the list that it fails. On the back end, it looks like it _MIGHT_ be incorrectly parsing the request when its sent though that method. 

This is what shows up in the npm output when you make a normal request using the 3pid integration method:
```
node-pre-gyp info MatrixRoomHandler Got location request  discord { channel_name: '#_discord_123456_123456',
node-pre-gyp info MatrixRoomHandler   guild_id: '123456' }
```
I don't know exactly how things work on the back end but from the looks of that report, its parsing the guild_id fine, but not the channel_name. I tried helping it along by modifying my request to just have the room ID since it seems to be getting the guild_id from the 3pid selection. That also didn't work and gave the same errors. Let me know if you guys need more info and what info.

**Comment by Sorunome** [comment]
Is this still the case? A few things were fixed that could be related to this

**Comment by bluesaxman** [comment]
Sorry for the delay getting back you to on this. Its been a while since I opened it so I'm going off my original discription to test it. It seem to work without issue now. I think this can be closed.
