### ISSUE TITLE
Accept Guild/Channel ID as x/y

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#273]
Whenever one has to paste the Guide and Channel ID from the Discord Web UI, they always have to do a little pre-processing to make it fit the `!discord bridge x y` template.

It would be nice if the bridge also accepted `!discord bridge x/y` for convenience's sake. Just split on the `/` if it exists.

**Comment by Sorunome** [comment]
got merged
