### ISSUE TITLE
Bridge aliases as matrix.to links

### ISSUE THREAD

**Issue by swedneck** [Half-Shot/matrix-appservice-discord#274]
Currently if a matrix user sends a pill link to #room:domain.com it's sent as plaintext to discord, it should instead send https://matrix.to/#/#room:domain.com to discord.

**Comment by Sorunome** [comment]
Also, if the link is from a discord-bridged channel, drop the `<#chanid>` thing instead

**Comment by Sorunome** [comment]
merged
