### ISSUE TITLE
Catch failures to sync user so they will still join the room

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#278]
https://github.com/Half-Shot/matrix-appservice-discord/pull/270/files#diff-8158defb0e7f6e3413c33cf1ef79408fR97

**Comment by Sorunome** [comment]
fixed in #270

https://github.com/Half-Shot/matrix-appservice-discord/pull/270/commits/afbc72cac4ce692f68b83d564d407c51c67e55ea#diff-8158defb0e7f6e3413c33cf1ef79408fL101

**Comment by Half-Shot** [comment]
@Sorunome I'm bad at explaining, I meant catch the OnUpdateUser because we always want to join the user to the room as a priority.

**Comment by Half-Shot** [comment]
Will close when soru merges #270

**Comment by Sorunome** [comment]
that was merged some time ago ^^
