### ISSUE TITLE
Deletion of bridged M>D message through discord, kills D>M bridging

### ISSUE THREAD

**Issue by TildeSlashC0re** [Half-Shot/matrix-appservice-discord#280]
We have reproduced this issue with the help of swedneck in the chat today.

**Version:** current `develop` branch // v.0.3.0-rc4

**Setup:**
* Matrix Room with PL-99 Discordbot
* Discord Channel with fully privileged Discordbot

**Scenario:**
1. User (any PL) sends message from matrix room to Discord channel
1. Discord user with sufficient privileges deletes bridged message on Discord

**Expected:**
Message on Discord is deleted, Message in matrix room is redacted. 

(current) **Reality:**
Message on Discord is deleted, Message in matrix room remains, bridge goes into one-way mode and stops relaying messages posted in discord to the matrix room.  
Typing indicator is alive though. 

**Relevant Logs:**

[![](https://i.imgur.com/094fYQSl.png)](https://i.imgur.com/094fYQS.png)

[![](https://i.imgur.com/qbMSWR5l.png)](https://i.imgur.com/qbMSWR5.png)

```js
Oct-30 20:49:13.695 [DiscordBot] info: Got delete event for 506916416826376209                                                                                               
Oct-30 20:49:13.696 [DiscordBot] info: Deleting discord msg 506916416826376209                                                                                               
Oct-30 20:49:13.699 [DiscordAS] verbose: matrix-appservice-bridge [-] POST https://0xbtfd.one/_matrix/client/r0/rooms/!hEFOwjLzeiLJFayavZ%3A0xbtfd.one/redact/%241540928682334
01CrdLP%3Amatrix.org (@_discord_506884211655835649:0xbtfd.one) Body: "{}"                                                                                                    
Oct-30 20:49:13.714 [DiscordAS] verbose: matrix-appservice-bridge [-] POST https://0xbtfd.one/_matrix/client/r0/rooms/!hEFOwjLzeiLJFayavZ%3A0xbtfd.one/redact/%241540928682334
01CrdLP%3Amatrix.org (@_discord_506884211655835649:0xbtfd.one) HTTP 403 Error: "{\"errcode\":\"M_FORBIDDEN\",\"error\":\"Application service has not registered this user\"}"
(node:32667) UnhandledPromiseRejectionWarning                                                                                                                                
(node:32667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
rejecting a promise which was not handled with .catch(). (rejection id: 16)                                                                                                  
(node:32667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
ess with a non-zero exit code.
```
[![](http://imgur.com/CKQ8R61l.png)](https://i.imgur.com/CKQ8R61.png)

[![](https://i.imgur.com/EFUBltfl.png)](https://i.imgur.com/EFUBltf.png)

```js
(node:32667) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 18)                                                                  
(node:32667) UnhandledPromiseRejectionWarning                                                                                                                                 
(node:32667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). (rejection id: 19)          
```
>> #279 

So effectively the bridge is one way at this point. And it's hard to tell what's causing it. 
It should also be noted that redacted messages on matrix will be deleted on discord without any issue.

***

[![](https://i.imgur.com/zZCEHR8l.png)](https://i.imgur.com/zZCEHR8.png)

**Comment by Half-Shot** [comment]
I've pushed https://github.com/Half-Shot/matrix-appservice-discord/commit/1f6fdf416cc5468db5172b20bbfa37cd57848e33 to develop, does that fix things?

**Comment by TildeSlashC0re** [comment]
works like a charm!
