### ISSUE TITLE
Unbridge from Discord side

### ISSUE THREAD

**Issue by BurnyBoi** [Half-Shot/matrix-appservice-discord#283]
I bridged a matrix room to a discord room using this public bridge: https://t2bot.io/discord/ ...and then left the Matrix room without unbridging.  I'm unable to get back in since it was invite-only, and I was the only one in it, so now it's just the Matrix bot in the room. I am concerned that messages sent in the discord room are still being bridged even though no one is in there.

Is there a way to unbridge from Discord? If not, this would be a valuable feature to have in case this happens.

**Comment by Half-Shot** [comment]
You need to contact @turt2live to manually remove the bridge, but yes we should have a discord command to unbridge rooms on discord.

**Comment by Sorunome** [comment]
implemented
