### ISSUE TITLE
Better parsing for various embed fields.

### ISSUE THREAD

**Issue by TildeSlashC0re** [Half-Shot/matrix-appservice-discord#284]
As is, parsing embeds currently leaves out some fields that are provided by the discord spec, which can lead to dissatisfying results on the matrix-side of things. 

I can provide screenshots if necessary.

**Comment by Sorunome** [comment]
> I can provide screenshots if necessary.

would be cool! And as embeds are commonly triggered by discord bots, would be also cool if you could say which ones so that soru can do better development on it ^^

**Comment by TildeSlashC0re** [comment]
![](https://i.imgur.com/P3yMiVS.png)

That'd be one example. 
The main focus here being the `undefined` string instead of the desired `AK // Our Destination` ... that's the `author` ([reference](https://leovoel.github.io/embed-visualizer/)) field in this case.

**Comment by Sorunome** [comment]
@TildeSlashC0re which bot is that you are using? Soru is looking into it and is a bit puzzled on the `undefined` currently

**Comment by Sorunome** [comment]
Should be greatly improved with #404 and #420
