### ISSUE TITLE
We don't handle webhook messages properly on Discord -> Matrix

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#287]
Because they don't have a discord user with an ID or anything, the bridge freaks out when it sees one. We need to create our own ID format for webhooks like `@_discord_webh_123456:domain`

**Comment by Sorunome** [comment]
looked into it, discord snowflakes are unique so that there are no collissions between webhook IDs and user IDs, so unneeded!
