### ISSUE TITLE
Bridge can easily crash when sending messages to large guilds due to logging

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#293]
The following lines cause memory issues in large guilds due to all the members also being logged:

https://github.com/Half-Shot/matrix-appservice-discord/blob/bfa258d0f758a2d27fbd00d54a5639fa4b7b3025/src/bot.ts#L246

https://github.com/Half-Shot/matrix-appservice-discord/blob/bfa258d0f758a2d27fbd00d54a5639fa4b7b3025/src/bot.ts#L324

**Comment by turt2live** [comment]
Opening as an issue because I'm not sure if the best approach is to remove them or log the information that is useful.

**Comment by Half-Shot** [comment]
Fixed in f8e5d143569d82cd7cab6b39f5ad66a40b4c3487
