### ISSUE TITLE
Bot mentions users with special characters in name when messaging matrix -> discord

### ISSUE THREAD

**Issue by colonelkrud** [Half-Shot/matrix-appservice-discord#32]
Updated with:
`get pull
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 34 (delta 23), reused 24 (delta 23), pack-reused 8
Unpacking objects: 100% (34/34), done.
From https://github.com/Half-Shot/matrix-appservice-discord
   a956b18..9c1b5be  develop    -> origin/develop
Updating a956b18..9c1b5be
`

Then ran like normal:
` node ./build/src/discordas.js -p 9005 -c config.yaml`

The bot started adding mentions to an online user with special characters in their name to every character in the message from matrix. 
Matrix -> Discord message: test
Discord displays: @... t @... e @... s @... t @...

Logs are normal; no unusual error reporting,

**Comment by lunny** [comment]
Also encounter the problem.

![-1](https://user-images.githubusercontent.com/81045/29109711-9e8e2f9a-7d16-11e7-9930-43014a7b1882.png)

**Comment by lunny** [comment]
Maybe the wrong regex?
https://github.com/Half-Shot/matrix-appservice-discord/blob/master/src/discordbot.ts#L280

**Comment by anoadragon453** [comment]
@lunny Is this still a problem that you or anyone else is experiencing?

**Comment by lunny** [comment]
@anoadragon453 Yes. It's still a problem. see https://discord.gg/NsatcWJ

**Comment by anoadragon453** [comment]
Ah yeah, I see.

@Half-Shot For reference the message I saw that was broken was the
following:

> Anyway, this is still probably @not the right room for such content

**Comment by anoadragon453** [comment]
And this.
![2017-09-11-202040](https://user-images.githubusercontent.com/1342360/30306750-ee3bd93e-972e-11e7-8163-7b70752f8a4a.png)

**Comment by Half-Shot** [comment]
Wow, it's still quite aggressive :s

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-appservice-discord/commit/a66e9f72df59ce29312308f8b091301a4065c45b should make this feature less aggressive but I'm tempted to either require an @ or drop the feature altogether.

**Comment by Half-Shot** [comment]
OR attempt to match Riot's nonstandard mention format.

**Comment by anoadragon453** [comment]
Requiring a @ would look strange with other services like IRC.

Perhaps once user pills are standard on mobile we should only follow
that? Or is that too Riot-specific?

**Comment by anoadragon453** [comment]
@lunny Could you try the latest commit on develop and report if the issue still persists?

**Comment by Half-Shot** [comment]
Merging discussion of #21 into this issue.

**Comment by jcgruenhage** [comment]
> OR attempt to match Riot's nonstandard mention format.

Is that hard? Riot's mentions are just the name with a link to matrix.to to their mxid.

**Comment by Half-Shot** [comment]
This has been continued in #46 to some extent.

**Comment by Half-Shot** [comment]
Closing in favor of #46
