### ISSUE TITLE
Have replies tag the user

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#335]
in discord embeds you an do `[](<@userid>)` to silently ping people. Suggestion by devie

**Comment by Half-Shot** [comment]
Do we want to let users be silently pinged outside of intentional use cases btw?

**Comment by Sorunome** [comment]
What do you have in mind? M->D parsing to filter out the discord regexes to other stuff, like inserting a zero-width space to prevent pings? we could do that

**Comment by Sorunome** [comment]
it appears that discord embeds don't ever ping the user no matter what --> this is impossible to do due to discord being discord

**Comment by Sorunome** [comment]
added
