### ISSUE TITLE
Webhooks (D->M) do not bridge nicely

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#359]
Heavily blurred to protect privacy, however:
![image](https://user-images.githubusercontent.com/1190097/50503759-7f29ed80-0a26-11e9-9971-390ce0f14325.png)

This is a Minecraft/Discord bridge being brought over to Matrix. It appears to operate by using webhooks to Discord which then bridge down through the Matrix bridge. 

This isn't great because it generates a ton of state changes, making the room harder to calculate and takes up a lot of space. Additionally, it adds noise to the chat.

What's going on in the image above is the light brown user talks, then another webhook comes in for the dark brown user. Instead of the Matrix/Discord bridge creating a new user, it reuses the light brown user. It then switches back at the end due to off-screen messages. This goes on for quite a while.

**Comment by Sorunome** [comment]
so a ghost per webhook id per display name?

**Comment by turt2live** [comment]
That might be best, perhaps a config option to toggle that behaviour?

**Comment by Sorunome** [comment]
Implemented!
