### ISSUE TITLE
Bots who are silent in Matrix should be silent in Discord

### ISSUE THREAD

**Issue by alexgleason** [Half-Shot/matrix-appservice-discord#363]
I don't know if this is possible on the Discord side, but some bots in Matrix know not to make noise or create a notification for the user. The [Matrix GitLab bot](https://t2bot.io/gitlab) creates a message for every commit, issue comment, etc and it's great on the Matrix side because the info is there if you go looking, but it doesn't notify anyone. It **does** seem to notify people on the Discord side, though, which is a little more information than people want.

Is it possible to check if the message comes from a bot and send it silently into Discord?

Thank you!

**Comment by Sorunome** [comment]
as of #316 that isn't the case anymore (so newest on develop branch). Thanks for reporting, though!
