### ISSUE TITLE
Unable to register bot user error after restarting bridge

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#37]
Right, so after upgrading the bridge to a new commit, I tried regenerating the config file and seem to have gotten myself into quite a pickle. At the moment, the bot can POST user's messages from Discord into Matrix, but it's not sending messages back over from Matrix to Discord.

Doing some digging, I found the following in the logs:

```
verb matrix-appservice-bridge [-] POST http://public.url:8008/_matrix/client/r0/register (AS) Body: {"auth":{},"username":"_discord_306101814091055113"}
verb matrix-appservice-bridge [-] POST http://public.url:8008/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_USER_IN_USE","error":"User ID already taken."}
...
verb matrix-appservice-bridge [-] PUT http://public.url:8008/_matrix/client/r0/presence/%40_discord_342097752093884417%3Apublic.url/status (@_discord_342097752093884417:public.url) HTTP 403 Error: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}
```

It seems that the bot is trying to re-register the same user, and not handling the error if that user already exists, thus getting errors down the line as it tries to use that user which it wasn't allowed to create.

Instead, it would be best if it could realize that the user was already registered and just log in as them, or barring that, create a new user with a different name if the user_id is already taken.

**Comment by anoadragon453** [comment]
To clarify, it's trying to re-register the room users (ie. Discord users). However since messages are getting relayed from Discord to Matrix still, perhaps this isn't the error message that's causing the bridge to not relay from Matrix to Discord.

**Comment by Half-Shot** [comment]
A failed registration won't be a failure point (and if it was, this is an issue with the appservice-bridge lib)

**Comment by anoadragon453** [comment]
Hm, maybe it's just coincidence then.

Not sure what has caused the bridge to stop relaying messages from Matrix to Discord. I assume that maybe it can't read the `/sync` stream for some reason, because it can still send messages and typing notifications and presence updates to matrix, but it isn't sending anything back.

[Here's a log on log-level silly, if it brings any insight.](https://gist.github.com/anoadragon453/f55d580c08378ecc1863eacf5ece5b7b) It starts from when the bot is started, and I sent many messages on both Discord and Matrix.

**Comment by anoadragon453** [comment]
Just re-cloned and went through the setup again. Worked fine after that.
