### ISSUE TITLE
Delete edited message instead of strike-out

### ISSUE THREAD

**Issue by tebjan** [Half-Shot/matrix-appservice-discord#375]
currently it looks very messy when discord users edit their message. often gets unreadable and confusing.
as long as matrix cannot edit messages, it would look so much cleaner to post the new edited message and when arrived, delete the previous one.

if you tell me where to find this functionality i would try to start working on it. this annoys me every day :)
otherwise, great job!

**Comment by Sorunome** [comment]
this was just merged today! #351 

Thank you for reporting, though!

**Comment by tebjan** [comment]
hah... 💃

**Comment by Sorunome** [comment]
>  do you know when the new version will roll out and has effect?

in a few min we'll be putting up an RC ^^

**Comment by tebjan** [comment]
for some days it was nice, but now i see the bad old habits coming back... what was the reason for that?

**Comment by Sorunome** [comment]
are you up-to-date on the master or develop branch? Currently the newest version is 0.4.0

**Comment by tebjan** [comment]
wait... sorry for ranting. there is mixed behavior actually:
![image](https://user-images.githubusercontent.com/1094716/51432445-67661380-1c38-11e9-952b-f81bc2427a67.png)
might just be a bug...

**Comment by Sorunome** [comment]
reason being is that a message was posted in between the original message and editing, thus deleting and re-sending would severely mess up conversation flow. This is on purpose
