### ISSUE TITLE
Refactor - 2019 edition

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#377]
- [x] Move user/room store to a postgres format (not sure yet whether do to at this level, or bridge lib level).
  - [x] Rooms
  - [x] Users
- [x] `Bluebird` should be obliterated, and we should find some util functions to replace it. #448 
- [x] Simplify M->D sending code.
- [x] Provisioner code should be taken out `bot.ts`, and use @Sorunome command code.
- [x] Matrix commands to use soru's command code. (and some of the discord stuff)
- [x] Refactor store function names. https://github.com/Half-Shot/matrix-appservice-discord/pull/455
- [x] ~Replace some funcs with idbdata functions.~ The only ones left are the user_id <=> discord_id+token mappings, which are quite complicated to merge into the idbdata format. I'm happy to leave this for another time, as it's not really used much anyway.
- [x] ~Remove `log.ts`~ Let's not do this now, since the move to the bot-sdk in #454 will leave us with no ability to log.
- [x] Take a look at circular dependencies in `discordas.ts` initialization logic.
- [x] `    "getbotlink": "node ./build/tools/addbot.js",` weird name.
- [x] Remove `getSchemaVersion` #391 
- [x]  `bot.ts` should not be at the center of processing events, factor out this.

**Comment by Half-Shot** [comment]
Did #378 actually enforce " bot.ts should not be at the center of processing events, factor out this." further?

**Comment by Sorunome** [comment]
Fully done! :tada:
