### ISSUE TITLE
Config option to make new rooms non-public by default

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#38]
Users of my bridge can connect to any discord channel, and it'll display on the public room directory.

...This might not be ideal, for reasons.

The ability to tell the bot to mark new rooms as not public (specifically to set [m.room.join_rules](https://matrix.org/docs/spec/client_server/r0.2.0.html#m-room-join-rules) to 'invite' instead of 'public'), would be really helpful!

**Comment by Half-Shot** [comment]
Yes, was wondering the same thing.

**Comment by Half-Shot** [comment]
Changes have been merged. Closing
