### ISSUE TITLE
Embeds bridged to matrix do not contain images

### ISSUE THREAD

**Issue by swedneck** [Half-Shot/matrix-appservice-discord#390]
Tested in 2 different chats hosted on separate machines, i'm unable to find any relevant errors in logs.

**Comment by Sorunome** [comment]
do the discord bots, by any chance, actually leave embeds instead of images?

**Comment by swedneck** [comment]
They do

**Comment by Half-Shot** [comment]
Adjusted title to ensure we don't mistrack this as a bug.

**Comment by Sorunome** [comment]
This was added in #404
