### ISSUE TITLE
Send messages from discord to matrix and reciprocally

### ISSUE THREAD

**Issue by floviolleau** [Half-Shot/matrix-appservice-discord#42]
Hi,

I successfully installed the bridge, configured it and run it. I configurated the HS but maybe I missed something...

1. I can see the room in matrix and the bot user.
2. I have the bot in discord.
3. I typed a message in matrix but it never comes in the discord chat and reciprocally
4. The bridge is running
5. The HS is running and has registered the bridge at startup

Here is my configuration (config.yaml):
```
bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
  disablePresence: false
  disableTypingNotifications: false
  disableDiscordMentions: false
auth:
  clientID: "blablabla" # Get from discord
  secret: "blablabla"
  botToken: "blablabla"
logging:
  level: "warn" #silly, verbose, info, http, warn, error
database:
  filename: "discord.db"
```

```
info discordas Starting Discord AS
info discordas Initing bridge.
info AppServ Started listening on port 9005 at Wed, 13 Sep 2017 22:44:52 GMT
info discordas Initing store.
info DiscordStore Starting DB Init
info DiscordStore Opening SQLITE database discord.db
info DiscordStore Updated database to the latest schema
info discordas Initing bot.
info DiscordBot Discord bot client logged in.
verb DiscordBot Bulk presence update
verb matrix-appservice-bridge [-] PUT http://localhost:8008/_matrix/client/r0/presence/%40_discord_107486792604712960%3Alocalhost/status (@_discord_107486792604712960:localhost) Body: {"presence":"online"}
verb matrix-appservice-bridge [-] PUT http://localhost:8008/_matrix/client/r0/presence/%40_discord_357636529696276482%3Alocalhost/status (@_discord_357636529696276482:localhost) Body: {"presence":"online"}
info discordas Discordbot started successfully.
verb matrix-appservice-bridge [-] PUT http://localhost:8008/_matrix/client/r0/presence/%40_discord_107486792604712960%3Alocalhost/status (@_discord_107486792604712960:localhost) HTTP 403 Error: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}
verb matrix-appservice-bridge [-] PUT http://localhost:8008/_matrix/client/r0/presence/%40_discord_357636529696276482%3Alocalhost/status (@_discord_357636529696276482:localhost) HTTP 403 Error: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}
```

Any clues ?
Thanks for your help.

**Comment by Half-Shot** [comment]
Your domain should be the external domain that you are using, not localhost. Same with homeserverUrl.

**Comment by floviolleau** [comment]
Thanks for your quick reply.

Now I face to:

`PUT https://exemple.org/_matrix/_matrix/client/r0/presence/%40_discord_107486792604712960%3Aexemple.org/status (@_discord_107486792604712960:exemple.org) HTTP null Error: {"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}`

**Comment by anoadragon453** [comment]
Do you have a self-signed certificate that you are using for HTTPS on your server?

If so, there may be an option to allow self-signed certs, but you're much better off getting a full, free certificate from the [Let's Encrypt](https://letsencrypt.org/) project. DigitalOcean have [great](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) [guides](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04) on how to set this up.

**Comment by floviolleau** [comment]
Yes.

I cannot use let's encrypt because I use a free dns by noip which is a sub domaine.

Any luck to change a bit inside the code?

**Comment by Half-Shot** [comment]
There isn't a whole lot we can do from this side, the part that handles matrix requests goes to https://github.com/matrix-org/matrix-appservice-bridge

**Comment by floviolleau** [comment]
Okey thanks.

I will try tomorow at work to "grab" a matrix developper directly and talk with him

**Comment by floviolleau** [comment]
Okey so I finally succeded to get a true certificate with my dyn dns at noip. Let's close this.
