### ISSUE TITLE
Matrix Bot

### ISSUE THREAD

**Issue by LucesEnBabel** [Half-Shot/matrix-appservice-discord#423]
Hello, I don't know if I'm missing something or I haven't checked the docs, but I can't find instructions to invite the bot to my Matrix channels.

How can I do it?

**Comment by Half-Shot** [comment]
Are you trying to add the bot to discord, or invite the bot to your matrix rooms. For the former: 
- https://github.com/Half-Shot/matrix-appservice-discord#setting-up-discord

For the latter:

- https://t2bot.io/discord

**Comment by LucesEnBabel** [comment]
The latter.

I assume there's no way to self host the Matrix Bot, no?

**Comment by Half-Shot** [comment]
Yes, you can run the bridge yourself and then create the bot. Sadly it's either the former or the latter.
