### ISSUE TITLE
Documentation on bot roles in Discord that may stop a bridge

### ISSUE THREAD

**Issue by serra-allgood** [Half-Shot/matrix-appservice-discord#425]
Had a hell of a time figuring out why the bot was working on a fresh Discord server but not on one that I'm on all the time. It had to do with how roles are configured on the server and how bot roles are placed in the role hierarchy for a guild.

1. Bot roles always start at the bottom of the roles
2. Although you can assign any role to a bot, only roles that are lower in hierarchy (which is higher in position in the UI) will actually be applied to the bot in terms of permissions. So if you have a channel that prevents anyone from posting except for members with a certain role, this will prevent the bot from posting in that channel.
3. If the `@everyone` role is configured on individual channels to outright deny the `Manage Webhooks` permission, it will prevent the bot both from being able to create webhooks for the channel and post in the channel even if a hook exists.

Perhaps this is all well known to Discord devs, but it was very opaque to me and required digging into the API documentation to fully understand. Additionally, because I'm not a mod of the server I'm trying to bridge to, it took some raw API calls in Postman using the bot token for me to piece everything together.

I should be able to put together a PR for this documentation if it's deemed worthy of inclusion.

**Comment by Half-Shot** [comment]
To be honest, I'm not terribly sure how the role system works myself. It would be extremely useful if this was noted down in a markdown doc and PRed :)

**Comment by serra-allgood** [comment]
Turns out I was mistaken, so closing this issue
