### ISSUE TITLE
YouTube embeds without descriptions show 'undefined'

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#43]
![screenshot_20170916_045100](https://user-images.githubusercontent.com/1342360/30509224-a8400b2a-9a9a-11e7-8fbf-abf49c5a9bce.png)

Should check if it's null :P

Edit: vid: https://www.youtube.com/watch?v=MK6TXMsvgQg

**Comment by Half-Shot** [comment]
![screenshot from 2017-09-17 09-36-29](https://user-images.githubusercontent.com/2072976/30519332-b2878b8e-9b8b-11e7-8a21-0cb1f60d50f4.png)

Doesn't show the description fix, but the formatting is much improved.

**Comment by anoadragon453** [comment]
Looking very nice!
