### ISSUE TITLE
Strange looking user IDs are being created

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#449]
Noticed this in my postgres logs: `@_discord_redacted729_redacted729:t2bot.io` (numbers redacted, but they are the same in each segment)

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-appservice-discord/blob/9d429ee1b8dd942d7e8be115ff58a49bdcce9a70/src/bot.ts#L125 ?

**Comment by turt2live** [comment]
Ah, so it's intentional?

**Comment by Sorunome** [comment]
for webhooks, yes. That was to prevwbt the constant renaming of the ghost on the matrix side

Am 2. Mai 2019 15:28:14 MESZ schrieb Travis Ralston <notifications@github.com>:

**Comment by Half-Shot** [comment]
Closing as intentional.
