### ISSUE TITLE
Build MatrixMessageProcessor for each time an M->D message is processed

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#459]
because currently there is a `this.prop` thingy  that is been passed to it which contains data like room ID etc. That would mean that that part isn't threadsafe

**Comment by Half-Shot** [comment]
This seems like it could be inefficient, but not against it entirely. Can't we pass roomIDs into whatever func we are calling?

**Comment by Sorunome** [comment]
would have to be passed recursively thorugh all functions, so shouldn't be more taxing than creating an object briefly?

**Comment by Sorunome** [comment]
switching to https://github.com/matrix-discord/matrix-discord-parser will also fix this

**Comment by Sorunome** [comment]
implemented!
