### ISSUE TITLE
Mention parser is too strict

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#46]
![2017-09-17-043945](https://user-images.githubusercontent.com/1342360/30520442-6a33517a-9b62-11e7-9dc4-94894ff6b1b7.png)

Currently the regex code for mention parsing will only create a mention if we type the user's displayname exactly.

At the very least this should be case-insensitive, and at most allow for matching their Discord ID (username#1234) as well as everything previously mentioned with an '@' in front.

Text used in above image:
```
* Pouar
* pouar#5184
* @Pouar
* pouar
```

**Comment by Half-Shot** [comment]
I've had horrible trouble trying to get a regex that will accept and consume an '@', which is probably something someone else can conjure up. I'll write some more test cases for these and fix the others though.

**Comment by Half-Shot** [comment]
#48 fixes most of these cases, but still working on the @ solution.

**Comment by anoadragon453** [comment]
Awesome, making good progress on the webhook creation as well.

**Comment by anoadragon453** [comment]
![2017-09-17-210224](https://user-images.githubusercontent.com/1342360/30528847-93c08984-9beb-11e7-9c47-c13caec54c1c.png)

Looking great! Now just that pesky @...

Text used in above image:

```
* Violet
* violet
* violetray#1234
* @violet
```

**Comment by Half-Shot** [comment]
@anoadragon453 Are you happy that the linked test case is covering your issue? I'll close it if so.

**Comment by anoadragon453** [comment]
The bridge now seems to only create username mentions for Riot pills. This seems sufficient and in line with Discord on Desktop, but does it work on Android mobile where pill creation isn't yet supported?

**Comment by Half-Shot** [comment]
@anoadragon453 it seems to be okay for me? Or rather I can still do the android style mentions ``$USER:`` and Riot ``@$USER``

**Comment by Half-Shot** [comment]
Going to close pending feedback.

**Comment by anoadragon453** [comment]
Yeah haven't had any issues lately with it :)
