### ISSUE TITLE
Puppeted replies ignore reply text

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#522]
They look like normal messages which is very confusing

**Comment by Sorunome** [comment]
isn't that on purpsoe so that real users don't send embeds?

**Comment by Half-Shot** [comment]
Yes, but it would be better if we did a:

```
>Roy: Did you see that ludicrous display last night?

The thing about Arsenal is that they always try to walk it in.
```
```

**Comment by Sorunome** [comment]
oh, that'll be easy. Should soru add that to #521 ? It is semi-related

**Comment by Sorunome** [comment]
Done in #521
