### ISSUE TITLE
Bridge doesn't use the canonical alias when referencing rooms

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#523]
1. Bridge a Discord channel to Matrix
2. Set the canonical alias to something custom
3. In a different Discord channel (or even the same), reference the other channel
4. Note that the alias rendered in Matrix is for the portal room, not the bridged room.

**Comment by Sorunome** [comment]
How did you bridge? `!discord bridge` or via joining `#_discord_` ?

**Comment by turt2live** [comment]
`!discord bridge`

**Comment by Sorunome** [comment]
are you running a version which has https://github.com/Half-Shot/matrix-appservice-discord/blob/master/src/channelsyncroniser.ts#L167 ? Are you sure it hasn't been bridged multiple times?

If so, what is the content of the `m.room.canonical_alias` event on that room?

**Comment by turt2live** [comment]
I am using a version with that code. It would almost certainly be bridged multiple times because the portal room does exist in addition to the plumbed room.

The alias event is:
```
{
  "type": "m.room.canonical_alias",
  "sender": "@travis:t2l.io",
  "content": {
    "alias": "#redacted:example.org"
  },
  "state_key": "",
  "event_id": "$redacted:example.org",
  "origin_server_ts": 1562080969055,
  "unsigned": {
    "age": 1067
  },
  "room_id": "!redacted:example.org"
}
```

**Comment by Sorunome** [comment]
Does the portal room have an alias set? If so, it has multiple canonical aliases associated with that one room and just picks the first one it finds

**Comment by turt2live** [comment]
It would have whatever the bridge set - I haven't controlled or manipulated the portal room. Should probably prioritize plumbed over portal rooms imo.
