### ISSUE TITLE
Client ID treated as "non string"

### ISSUE THREAD

**Issue by McL0v1n** [Half-Shot/matrix-appservice-discord#532]
container doesnt start due to the following:

{"field":"data.auth.clientID","message":"is the wrong type","value":xxxxxxxxxxxxxxx400,"type":"string","schemaPath":["properties","auth","properties","clientID"]}

The client ID is converted to a non-string and the final 2 digits are changed to zeroes

Latest Build

**Comment by Sorunome** [comment]
You mean in docker?

**Comment by McL0v1n** [comment]
Yes, my bad. It was late when I submitted

**Comment by Half-Shot** [comment]
Have you tried specifying the client ID in quotes?

**Comment by Half-Shot** [comment]
Fixed by the above.

**Comment by McL0v1n** [comment]
I did try specifying in quotes. Still converted to a number. The only work around was to do double AND single quotes:

"'xxxxxxxxxxxxxxx'"

Sent from ProtonMail mobile

-------- Original Message --------
