### ISSUE TITLE
Redacting an already-redacted message causes another message to be deleted

### ISSUE THREAD

**Issue by auscompgeek** [Half-Shot/matrix-appservice-discord#539]
Described in https://github.com/matrix-org/matrix-appservice-slack/issues/173#issuecomment-514634204

When an `m.room.redaction` event comes in, redacting message A that has already been redacted, after message B was sent, message B is deleted on Discord, which then gets echoed back to Matrix.

**Comment by Sorunome** [comment]
duplicate of #422
