### ISSUE TITLE
Mentions should not be parsed if in a code block

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#55]
![2017-09-18-183705](https://user-images.githubusercontent.com/1342360/30572066-6f23e4f8-9ca0-11e7-91df-75b775bcfeb1.png)

![2017-09-18-183246](https://user-images.githubusercontent.com/1342360/30571969-d35d2340-9c9f-11e7-85fa-141f2fff3969.png)

Words that represent someone's name within a code block are parsed to their mention format, when they should instead be ignored in that context.

**Comment by Half-Shot** [comment]
I'm feeling like the best way to solve this is to just take the code blocks out during the parsing sections and replace them afterwards.

**Comment by anoadragon453** [comment]
Simple and solves the problem. I'd say that works fine.

Thanks,
Andrew Morgan

**Comment by Sorunome** [comment]
fixed
