### ISSUE TITLE
Feature to block users on different platforms

### ISSUE THREAD

**Issue by ingochris** [Half-Shot/matrix-appservice-discord#553]
Perhaps through use of  `/block identifier` command, if sdks do not allow button api hook.

**Comment by auscompgeek** [comment]
I'm confused. What exactly is this asking for?

If this is asking to be able to moderate, either from Matrix to Discord (#306), or from Discord to Matrix (#210), those are already a thing.

**Comment by ingochris** [comment]
Hi @auscompgeek,

To clarify, the aforementioned feature refers to giving users the ability to block one another, between platforms. Does matrix-appservice-discord already have this function?

**Comment by auscompgeek** [comment]
What do you mean by "block"? If you're referring to ignoring users, that's a client-side feature and already exists in Riot. Ignoring Matrix users on Discord is impossible unless you want to ignore _every_ Matrix user.

**Comment by ingochris** [comment]
Yes, that is the block (as termed in Discord) I'm referring to. It may be impossible, but one method I've theorized is making matrix puppets block-able by discord users through the bridge webhook.

As-is, users are joining Matrix to circumvent Discord blocks on a per-user basis (not server/channnel-wide ban or moderation levels).

**Comment by auscompgeek** [comment]
AFAIK, Discord incoming webhooks don't provide a way to hide messages from specific users.

**Comment by ingochris** [comment]
Yeah, and I'm guessing the webhook doesn't discriminate per user in Discord channels, either, so the matrix-appservice-discord server wouldn't be able to change who can view puppet messages in Discord, unfortunately.

**Comment by Half-Shot** [comment]
@ingochris It's already possible to kick/ban matrix users from the discord side. Blocking them from your personal view isn't something the bridge has any control over, and it likely never will do.
