### ISSUE TITLE
Support connection pooling

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#557]
`pg-promise` doesn't support this, but `pg` does. We should switch to it ideally.

**Comment by vitaly-t** [comment]
That's not true. Each [Database] object encapsulates the `Pool` type, and even exposes it via [$pool].

[Database]:https://vitaly-t.github.io/pg-promise/Database.html
[$pool]:https://vitaly-t.github.io/pg-promise/Database.html#$pool

**Comment by Half-Shot** [comment]
Aaaaaaah, so we have to do nothing :). Excellent.
