### ISSUE TITLE
Nicks aren't carried over until a nick-name change

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#56]
![2017-09-27-133344](https://user-images.githubusercontent.com/1342360/30936376-9132cffc-a388-11e7-8a97-eef8b83f360d.png)

![2017-09-27-133543](https://user-images.githubusercontent.com/1342360/30936457-cd3c9e56-a388-11e7-8170-ed0d84cb1e69.png)

Faux matrix user's display names don't reflect their nicks until they're changed. Should grab their nick initially rather than their discord usernames.

**Comment by Half-Shot** [comment]
This is partially resolved, however, we have a new upstream issue that still breaks this behaviour.
