### ISSUE TITLE
Template discord-registration.yaml

### ISSUE THREAD

**Issue by Flying--Dutchman** [Half-Shot/matrix-appservice-discord#562]
Where can I find a template discord-registration.yaml? 
Installing something just for the generation of a single file is a bit overkill IMHO.

**Comment by Half-Shot** [comment]
We currently expect you to install and run the automatic generator, but yes we should probably just provide a file. The #454 changes will expect this anyway.

**Comment by Flying--Dutchman** [comment]
Thank you for the info. Looking forward to the new version 👍
