### ISSUE TITLE
Webhooks sent in Discord carry over as a random user

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#57]
![2017-09-27-134619](https://user-images.githubusercontent.com/1342360/30936952-48516eea-a38a-11e7-889f-981d532172df.png)

![2017-09-27-134308](https://user-images.githubusercontent.com/1342360/30936839-ec151ffa-a389-11e7-8833-d76b122e75fe.png)

Alright, so here I'm doing an experiment with "editing" other user's messages. You send a message, the bot records it, deletes the original, then posts a new message as a webhook under your name and avatar.

This works fine on the Discord side as you can see from the above screenshot, but the bridge gets confused with the webhook talking in the channel and prints it as (in my experience) some random user.

The webhook isn't a real user on either Matrix or Discord, so I can see why it would be confused, but we should be able to still get the avatar and name of the webhook to pass it over the bridge, right? Maybe just have a fake user on the Matrix side for posting webhooks? Perhaps that user would change their nick and avatar every time to match the webhook's? :P

---

Edit: 
![2017-09-27-141350](https://user-images.githubusercontent.com/1342360/30938211-283488aa-a38e-11e7-8aad-be724e12499b.png)

![2017-09-27-141235](https://user-images.githubusercontent.com/1342360/30938207-251acc74-a38e-11e7-97cf-dd5b814def4b.png)

It seems that a new user is already created for the webhook, and it changes its name and avatar already based on the webhook. However if I spawn another webhook, the avatar and name *isn't* changed again (the Peppermint Lime#4801#0000 should be Violet Ray instead). Also I'm not sure what's up with the double #xxxx#xxxx's. Also my nick changed for some reason, when it shouldn't.

**Comment by Half-Shot** [comment]
Right, only just got around to this but it's probably going to block any sort of release.

So the bug is down to you editing another users message on discord and that translates to the rando message in Matrix?

**Comment by turt2live** [comment]
I've managed to have this happen in a test channel of mine before. No editing or anything fancy, just me saying "ping" and "pong" every once and a while. The channel is just me :(

**Comment by Half-Shot** [comment]
Hmm, then I will need to put proper trace logs in for the entire chain between discord and matrix and see if we can spot something.

**Comment by Half-Shot** [comment]
The above branch has enough tracing to hopefully work out the issue.

**Comment by Half-Shot** [comment]
https://riot.im/app/#/room/!UcYsUzyxTGDxLBEvLz:matrix.org/$15193061904713vOlQo:t2bot.io got our smoking gun!

**Comment by Half-Shot** [comment]
Got a lead: https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/src/bot.ts#L534 doesn't catch webhook messages.

**Comment by anoadragon453** [comment]
Exciting!

**Comment by Half-Shot** [comment]
Merged. Go go go!

**Comment by Half-Shot** [comment]
Closing. Will reopen if not fixed.
