### ISSUE TITLE
Not working on linux due to better-sqlite being broken on node lts 12

### ISSUE THREAD

**Issue by Nothing4You** [Half-Shot/matrix-appservice-discord#574]
`npm install` fails to install dependencies due to this bug

https://github.com/JoshuaWise/better-sqlite3/issues/310

**Comment by Half-Shot** [comment]
I believe this has since been fixed.

**Comment by fanch317** [comment]
[Fixed](https://github.com/JoshuaWise/better-sqlite3/issues/310#issuecomment-590351849) in **better-sqlite3 v6.0.1** but matrix-appservice-discord v0.5.2 use **better-sqlite3 v5.4.3**.

You can [change this](https://github.com/Half-Shot/matrix-appservice-discord/blob/d313c627953c649fe9ac642aca5b2e48f6b5447d/package.json#L37) in package.json and run npm install again

#597
