### ISSUE TITLE
Question: Is it possible to use this bridge without having the bot join a guild?

### ISSUE THREAD

**Issue by gergof** [Half-Shot/matrix-appservice-discord#578]
If I use puppeting is it still needed to have the bot join the guild?

**Comment by Sorunome** [comment]
No, it isn't possible. Even if you puppet the bot still needs to be in the guild.

**Comment by gergof** [comment]
Ok. I will try to implement it myself then (if it is possible at all). :slightly_smiling_face:
I will report back if I succeed.

**Comment by Sorunome** [comment]
mx-puppet-discord will get that feature soon (a puppeting-based discord bridge, currently only dping DMs)

Am 20. Dezember 2019 09:01:13 MEZ schrieb "Fándly Gergő" <notifications@github.com>:
