### ISSUE TITLE
Scripts shouldn't need to sync to do an action

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#58]
Scripts like the adminme script shouldn't need to sync to work. In cases where the discord bridge is potentially in hundreds of rooms, the js-sdk times out trying to get the initialSync done. Settings power levels for a room does not require syncing and it shouldn't need to.

For reference, here's the script I use to admin people on t2bot.io: https://gist.github.com/turt2live/f3de58d79aff02da0b2291031c87a6ec
It intentionally doesn't sync and just does a fetch of the current event and populates the required parts. It does make some assumptions about file names, however.

**Comment by johnyhlee** [comment]
This functionality has been completely disabled in synapse as of Synapse 0.27.1, and thus the `adminme` script does not work anymore. 

See: matrix-org/matrix-doc#1144
