### ISSUE TITLE
Room Does not Exist

### ISSUE THREAD

**Issue by jthomas2234** [Half-Shot/matrix-appservice-discord#587]
![roomnoshowing](https://user-images.githubusercontent.com/33244451/75601991-e356a000-5a75-11ea-96f5-5a0432bbccfd.png)
/join used to work now it doesn't work checked the logs and couldn't really find anything not sure whats wrong.

**Comment by hockeymikey** [comment]
@jthomas2234 What was your resolve on this?

**Comment by jthomas2234** [comment]
So what was wrong was the bot I added needed to be the bot from a friends home server I was using so I needed the bots ID key and needed to add it through discord, then when I tried to addd the discord room with the guild ID and channel ID it worked
