### ISSUE TITLE
Bridge Message Edits

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#60]
![screenshot_20170930-083045](https://user-images.githubusercontent.com/1342360/31047222-5be0827e-a5bb-11e7-920f-87daf5c58838.png)

This is how the gitter bridge shows message edits without the ability to edit messages on the matrix side and I thought it was *gorgeous*. The repo for that bridge is [here](https://github.com/matrix-org/matrix-appservice-gitter).

I do not believe you can edit webhook messages, but once/if matrix gets message editing capabilities, we can send a similar message on the discord side, however perhaps with italics rather than colors, as discord is monocolor.

**Comment by Half-Shot** [comment]
Done thanks to @anoadragon453 !
