### ISSUE TITLE
Add community flair for puppets

### ISSUE THREAD

**Issue by Scrumplex** [Half-Shot/matrix-appservice-discord#614]
Similar to how the IRC Bridge does that, there should be a configurable option to give every Discord -> Matrix puppet a community flair, in addition to adding the community to all bridged channels.

An example of this would be the +freenode:matrix.org community.

**Comment by Sorunome** [comment]
That is already configurable, you can add it in the registration file. that is a synapse feature, not something bridges have to implement. Not sure atm what the setting name in the registration file is for that...

**Comment by Scrumplex** [comment]
> That is already configurable, you can add it in the registration file. that is a synapse feature, not something bridges have to implement. 

Well... 

I think I will be closing this :D
