### ISSUE TITLE
Matrix Mesages Not Being Sent to Discord

### ISSUE THREAD

**Issue by fhrach4** [Half-Shot/matrix-appservice-discord#630]
After upgrading to v1.0.0-rc3, the 'bot' User on the Matrix side never appears online and never relays messages to bridged Discord rooms. Messages from Discord are still sent, and users are still updated properly in the Matrix room, despite this. I  upgraded to the latest version of Synapse and that did not resolve the issue.

Unfortunately, there is no error or logging information that I can provide beyond the following line from the Synapse startup sequence.

```2020-11-17 10:06:05,361 - synapse.config.appservice - 87 - INFO - None - Loaded application service: ApplicationService: {'token': '<redacted>', 'url': 'http://localhost:9005', 'hs_token': '<redacted>', 'sender': '@_discord_b
ot:<redacted>', 'server_name': '<redacted>, 'namespaces': {'aliases': [{'exclusive': True, 'regex': re.compile('#_discord_.*')}], 'rooms': [], 'users': [{'exclusive': True, 'regex': re.compile('@_discord_.*')}]}, 'id':
 'discord-bridge', 'ip_range_whitelist': None, 'supports_ephemeral': False, 'protocols': {'discord'}, 'rate_limited': False}```

Thanks in advance, and I apologize if this is not the correct place to raise this issue.

**Comment by lapin-b** [comment]
I have just updated my bridge installation to the latest version (version 1.0.0 at the time of writing this comment) and messages are relayed in both directions.

Hopefully, updating your installation will fix your issue :)

**Comment by verymilan** [comment]
same here (i guess) - i was coming from the old master branch and updated to v1.0.0. i didn't have crying users yet for some reason but the room i manage now only sends status messages like join/leaves - including from the irc bridge. would be nice to have the messages too^^
if there is any additional information i can provide to investigate, i am happy to respond asap.

**Comment by auscompgeek** [comment]
Stab in the dark: what version of nodejs is everyone here running?

**Comment by fhrach4** [comment]
I have a slight update on this issue.

After upgrading to v1.0.0 I started getting the following error message:
`Dec-7 17:13:41.108 [DiscordBot] warn: Failed to send message $5Lp4iri_yuu6w_cnkRTAs1HLyX7uSygwEuOwT57o6eY`.
This was after a full re-install and manually deleting all of the ghost users that the bot created in Matrix. Once again, messages can come from Discord to Matrix, but, messages from Matrix to Discord seem to hit that error. I'll keep looking into this in my spare time, which, I should have more of over the holidays.

As for my nodejs version, I'm on v10.21.0 on CentOS 8.

Edit: realize I posted my npm version, not my node version.

**Comment by verymilan** [comment]
i feel stupid, i was still on 10.x - i have fixed this and am running 12 now - bridge is fixed!

**Comment by lapin-b** [comment]
> Stab in the dark: what version of nodejs is everyone here running?

NodeJS version 13.14.0, from the APT repositories version 13.x provided by NodeJS

**Comment by auscompgeek** [comment]
@fhrach4 Per the readme, Node 10 is no longer supported. I believe this is because discord.js upstream dropped support for Node 10. If you turn the logging up to verbose, you will likely see an error from discord.js.

**Comment by fhrach4** [comment]
Thanks a lot for your help, I think I have everything working again. Manually upgrading CentOS8 to use Node 12 seems to have done the trick.

I deeply apologize for opening an issue for a simple fix, I must've read that over so many times but it didn't register.
