### ISSUE TITLE
Should the port number in package.json really be 9995?

### ISSUE THREAD

**Issue by yquemener** [Half-Shot/matrix-appservice-discord#632]
Hi! I am trying to understand this code, I suspect this line:

https://github.com/Half-Shot/matrix-appservice-discord/blame/develop/package.json#L12

has a typo introduced in that commit:
https://github.com/Half-Shot/matrix-appservice-discord/commit/ca04d707cde048e004cec5e8003bb9e8efa12a64

Not 100% sure, but I fail to see what the 9995 port would be used for otherwise.

**Comment by jaller94** [comment]
The command line parameter overwrites the port configured in the config.
There's no harm in specifying a different port here, but I would just remove the parameter from the npm script `start` so that the port in the config is used.

**Comment by Half-Shot** [comment]
I can't recall why I did this. I suspect I changed the port for my own system and committed it by accident. #634 should fix it though.

**Comment by Half-Shot** [comment]
I believe #634 resolves this.
