### ISSUE TITLE
Avatars of Discord ghost users use WebP

### ISSUE THREAD

**Issue by mrjohnson22** [Half-Shot/matrix-appservice-discord#642]
After updating to v1.0.0, Discord user avatars are saved as webp files, preventing them from loading properly in clients like Element Web/Android, Fractal, and FluffyChat.

This results in some odd behaviour in Element Web, which is unable to load a webp avatar in some places (like in the message content area or in the user profile sidebar) but can in others (like when clicking on a user's profile image in the sidebar, which will load the proper image even though the sidebar cannot). Viewing a webp avatar directly via its media repository URL works though, as the "client" in that case is the web browser itself.

Maybe avatars should be converted to png before being stored it in the media repository.

**Comment by auscompgeek** [comment]
Your media repo doesn't support thumbnailing of WebP images. I believe all the clients you mentioned support WebP fine.

**Comment by mrjohnson22** [comment]
Ah, thanks. The media repo I'm using is the one that comes with Synapse. Is there a way to make it support WebP, or to perhaps make either Synapse or the Discord bridge convert WebP images to another format? I've also ran into the issue of WebP images being posted as Discord messages not getting bridged.

**Comment by auscompgeek** [comment]
Synapse uses the Pillow library for thumbnailing. You'll need to install whatever dependencies it needs for WebP support.

**Comment by mrjohnson22** [comment]
Thanks! I'll get on that now.
Closing since this is just a server-side issue on my end.

**Comment by mrjohnson22** [comment]
Here's the fix for anyone who runs into this:
* Install `libwebp` system libraries. For Debian 10, use `apt install libwebp6 libwebp-dev`.
* In Synapse's Python environment (virtual or otherwise), reinstall Pillow *making sure to bypass pip's cache*: `pip install --force-reinstall --no-cache-dir 'pillow>=4.3.0'`.

Reference: https://pillow.readthedocs.io/en/stable/installation.html#external-libraries
