### ISSUE TITLE
Quotes add an empty line and trailing greater sign

### ISSUE THREAD

**Issue by sagehane** [Half-Shot/matrix-appservice-discord#659]
#### Type of failure:
Matrix -> Discord

#### How to reproduce:
1. Send a message with a quote from Matrix.
![image](https://user-images.githubusercontent.com/74805176/103438417-de7cf280-4c2a-11eb-86a4-7e52fed67e46.png)
2. View the image on Discord
![image](https://user-images.githubusercontent.com/74805176/103438436-01a7a200-4c2b-11eb-9a75-40cb462307c8.png)

#### Intended Behavior:
There shouldn't be an empty line at the beginning, and a trailing greater sign at the end.

After asking on https://matrix.to/#/#help:t2bot.io, I was told the issue might be somewhere around [here](https://github.com/matrix-discord/matrix-discord-parser/blob/master/src/matrixmessageparser.ts#L243-L246)

**Comment by tgr** [comment]
I can't reproduce this as written; a single quoted line is translated correctly. Things get quite broken when quoted and unquoted content is mixed, though. Example source:
```
Quote test:
> this is quoted
```
Matrix:
![Element-Magyar-Wikipédia-Discord-tesztszoba (1)](https://user-images.githubusercontent.com/145412/147630519-b69f82cd-edf5-4758-bf55-e2a729aafd61.png)
Discord:
![matrix](https://user-images.githubusercontent.com/145412/147630563-ce168f74-3253-4160-bdb4-bcec7e759fa1.png)

**Comment by sagehane** [comment]
Thanks @tgr, I can confirm that the issue has been fixed by then. 

>Things get quite broken when quoted and unquoted content is mixed, though.

The problem you mentioned seems to be #750, which is that the bridge (or Discord?) seems to escape newlines.

I'm closing this issue, and #702 should also be closed too.
