### ISSUE TITLE
Rate limit joins to rooms

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#66]
Sending a couple thousand join requests is bound to fail

**Comment by Half-Shot** [comment]
Oh wait, we don't do this now. I'm sure we made it so that joins are 6 seconds apart.

**Comment by Sorunome** [comment]
don't we do this by now? https://github.com/Half-Shot/matrix-appservice-discord/blob/master/src/matrixroomhandler.ts#L513-L530

**Comment by Half-Shot** [comment]
I suspect we do and this is an old bug.
