### ISSUE TITLE
error: 'Unrecognised access token'

### ISSUE THREAD

**Issue by krishnerkar** [Half-Shot/matrix-appservice-discord#669]
I'm using the correct bot token in my `config.yaml` file, i even reset it and check it 3-4 times but the same error again and again

```
    'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization, Date'
    }
  },
  body: {
    errcode: 'M_UNKNOWN_TOKEN',
    error: 'Unrecognised access token',
    soft_logout: false
  },
  [Symbol(kCapture)]: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-appservice-discord@1.0.0 start: `npm run-script build && node ./build/src/discordas.js -c config.yaml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matrix-appservice-discord@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/krishnerkar/.npm/_logs/2021-01-21T17_41_24_000Z-debug.log

```

**Comment by Sorunome** [comment]
sounds like you didn't register your registration file with synapse & restart synapse?

**Comment by krishnerkar** [comment]
> sounds like you didn't register your registration file with synapse & restart synapse?

well i did copy the registration file inside the synapse folder, how to restart synapse, im not sure

**Comment by Sorunome** [comment]
depends on your distro and installation method, typically `systemctl restart synapse` or `systemctl restart matrix-synapse`

**Comment by Krish-Nerkar** [comment]
wait, i have a small doubt, in which folder do we have to run the following commands 
![image](https://user-images.githubusercontent.com/49949733/105394191-454a6600-5c43-11eb-80ec-a814b05a2afa.png)

**Comment by Sorunome** [comment]
This repository is not for general help on system administration. Please find appropriate help channels for learning how to maintain a server instead.

**Comment by krishnerkar** [comment]
Hey, its still not working, the restart commands are not working, im on linux, ubuntu
