### ISSUE TITLE
Is There Any Way To Remove The Bot Icon In Discord Next to the messages sent from the matrix client?

### ISSUE THREAD

**Issue by krishnerkar** [Half-Shot/matrix-appservice-discord#670]

**Comment by cloudrac3r** [comment]
no

**Comment by sjmonson** [comment]
https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/docs/puppeting.md may be what you are looking for.

**Comment by krishnerkar** [comment]
> https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/docs/puppeting.md may be what you are looking for.

Hey can you point out the file where the code for this particular functionality is there, I couldn't seem to find it
