### ISSUE TITLE
config option to disable portal linking/creation

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#673]
for public servers it's not entirely helpful to have this feature given it confuses people. 

The config option should:
* Disable new portal creation (based on joining the alias) - existing portals should work
* Disable automatic linking of #general -> #discord_id aliases (for new messages)

**Comment by turt2live** [comment]
maybe allow the linking to work if the room is known, but otherwise let it fail as-is?

**Comment by o080o** [comment]
I think some of this was already addressed in https://github.com/Half-Shot/matrix-appservice-discord/pull/663

**Comment by jaller94** [comment]
Fixed in #663 by the introduction of `bridge.disablePortalBridging`.
