### ISSUE TITLE
URL previews for images from Discord appear to bridge

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#68]
Discord:
![image](https://user-images.githubusercontent.com/1190097/31313941-af979af2-abaf-11e7-93c7-7357ba22ef4f.png)
Only the URL was sent, the image is a result of the Discord url previewing.

Riot/matrix:
![image](https://user-images.githubusercontent.com/1190097/31313952-da115142-abaf-11e7-839e-f8f94ec330b8.png)
Again, the image is a result of the URL preview.

The concern is with the strange-looking message that got bridged. Here is the source from Riot:
```
{
  "origin_server_ts": 1507437246988,
  "sender": "@_discord_215664408641273858:t2bot.io",
  "event_id": "$150743724620527VwIlZ:t2bot.io",
  "unsigned": {
    "age": 139
  },
  "content": {
    "body": "https://t2bot.io/img/logos/mx-discord.png\n\n----\n##### [undefined](https://t2bot.io/img/logos/mx-discord.png)",
    "msgtype": "m.text",
    "formatted_body": "<p><a href=\"https://t2bot.io/img/logos/mx-discord.png\">https://t2bot.io/img/logos/mx-discord.png</a></p>\n<hr>\n<h5 id=\"-undefined-https-t2bot-io-img-logos-mx-discord-png-\"><a href=\"https://t2bot.io/img/logos/mx-discord.png\">undefined</a></h5>\n",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!pDynKLEzozBZzARqct:t2bot.io"
}
```

**Comment by Half-Shot** [comment]
Looks like discord generate a preview attachment with the image. That's gonna be a royal pain to filter out.

**Comment by Half-Shot** [comment]
Can't seem to reproduce https://matrix.to/#/!PxMWbvomtRqGOTsaDK:half-shot.uk/%24152940628318VKYcR:half-shot.uk

**Comment by Half-Shot** [comment]
Yeah, managed to repro it.
