### ISSUE TITLE
bot in discord sending messages as embeds in specific server

### ISSUE THREAD

**Issue by shawnshyguy** [Half-Shot/matrix-appservice-discord#683]
Hi,
In the main Discord server I intend on using the bot in (which I do not own), messages send like so:
![image](https://user-images.githubusercontent.com/18062048/109604100-f076f680-7af0-11eb-8f0d-14fdd1096f94.png)
In 2 other servers I tested the bot in, messages send like so:
![image](https://user-images.githubusercontent.com/18062048/109604189-14d2d300-7af1-11eb-8421-8435a2b73e08.png)

Going to Integrations > Matrix in the offending server, Matrix [BOT] is granted webook permissions, but hasn't made any.
Like I said, I don't own the server, my friend does, so I can only see so much from my end, but as far as I can tell, role permissions (namely webhook management) are identical to permissions on my test servers where webhooks were made properly.

**Comment by auscompgeek** [comment]
There aren't any channel overrides that would affect webhook creation?

**Comment by shawnshyguy** [comment]
There weren't any channel overrides, but apparently the server was at max webhooks. My friend was able to move one of them, and now its working like normal.
