### ISSUE TITLE
Deleted channels are handled awkwardly

### ISSUE THREAD

**Issue by walle303** [Half-Shot/matrix-appservice-discord#69]
There should be some kind of indication when a channel is deleted, because in their current state, deleted channels do not show any sign of deletion, and can cause confusion.<br><br>Some of the following should be done to reduce confusion:<br><ul><li>Changing name/topic</li><li>Setting message sending power level to 100</li><li>Room directory delisting[Current homeserver only, obviously]</li><li>Unsetting appservice room alias</li><li>Setting invite only mode.</li><li>Parting all appservice ghosts</li><li>Stop bridging join/parts&avatar/nick changes</li></ul><br>

**Comment by Sorunome** [comment]
fixed / handled
