### ISSUE TITLE
New Discord replies aren't mirrored to Matrix

### ISSUE THREAD

**Issue by igeljaeger** [Half-Shot/matrix-appservice-discord#706]
Discord implemented a new reply system a year ago or so which does not mirror to matrix at all. It used to be a manual quote but this changed and now only works from Matrix to Discord but not the other way around.

**Comment by jackmawer** [comment]
This might be a duplicate of #631, and is related to #693.

**Comment by BBaoVanC** [comment]
This would be solved by #704

**Comment by rollingmoai** [comment]
This should be closed as a duplicate of #631.
