### ISSUE TITLE
Error on npm start after new install

### ISSUE THREAD

**Issue by V1TA5** [Half-Shot/matrix-appservice-discord#713]
I get the following when i try  npm start

> matrix-appservice-discord@1.0.0 start
> npm run-script build && node ./build/src/discordas.js -c config.yaml

> matrix-appservice-discord@1.0.0 build
> tsc

src/discordas.ts:95:26 - error TS2345: Argument of type '{ debug: (mod: string, args: any[]) => void; error: (mod: string, args: any[]) => void; info: (mod: string, args: any[]) => void; warn: (mod: string, args: any[]) => void; }' is not assignable to parameter of type 'ILogger'.
  Property 'trace' is missing in type '{ debug: (mod: string, args: any[]) => void; error: (mod: string, args: any[]) => void; info: (mod: string, args: any[]) => void; warn: (mod: string, args: any[]) => void; }' but required in type 'ILogger'.

 95     LogService.setLogger({
                             ~
 96         // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
103         warn: (mod: string, args: any[]) => logFunc("warn", mod, args),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
104     });
    ~~~~~

  node_modules/matrix-bot-sdk/lib/logging/ILogger.d.ts:35:5
    35     trace(module: string, ...messageOrObject: any[]): any;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'trace' is declared here.

Found 1 error.

Its a fresh ubuntu 20 install. I also had problems running npm update

npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: matrix-appservice-discord@1.0.0
npm ERR! Found: eslint@7.28.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from @typescript-eslint/parser@2.34.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^2.14.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^2.0.0" from @typescript-eslint/eslint-plugin@2.34.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^2.14.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-12T06_04_55_577Z-debug.log

**Comment by ghost** [comment]
I think I got something similar, it was just a matter of making sure that all the dependencies were installed (in my case debian I had to install the latest versions of node,yarn,npm) and then if you still get that just do npm install --legacy-peer-deps

**Comment by V1TA5** [comment]
61 verbose stack Error: command failed
61 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
61 verbose stack     at ChildProcess.emit (node:events:394:28)
61 verbose stack     at maybeClose (node:internal/child_process:1067:16)
61 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
62 verbose pkgid matrix-appservice-discord@1.0.0
63 verbose cwd /srv/matrix-appservice-discord
64 verbose Linux 5.4.119-1-pve
65 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--legacy-peer-deps"
66 verbose node v16.3.0
67 verbose npm  v7.15.1
68 error code 2
69 error path /srv/matrix-appservice-discord
70 error command failed
71 error command sh -c npm run build
72 verbose exit 2

**Comment by auscompgeek** [comment]
I cannot reproduce with `yarn && yarn build` (specifically using `/nix/store/l1ijbd3fbifqqdyrib1k5dpmjzw3j7db-yarn-1.22.10`).

**Comment by jaller94** [comment]
Ubuntu 20 ships the unsupported NodeJS 10 by default.
Please re-open the issue, if this is happening with a recent Node version.

Also, please use `yarn` to install dependencies to benefit from `yarn.lock`, if possible.
