### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by avivace** [Half-Shot/matrix-appservice-discord#716]
It looks like this repository is pretty much abandoned from the mainterners, while it's still getting a lot of attention and quality PRs. Why are those being ignored for months?

@Half-Shot wouldn't it make sense to look for contributors and give write access to someone else, too?

**Comment by Sorunome** [comment]
All current maintainers gut super busy over the past few months :(

22. 6. 2021 9:52:16 Antonio Vivace ***@***.***>:

**Comment by OmeGak** [comment]
Any chance you guys could add @Flam3rboy as maintainer (https://github.com/Half-Shot/matrix-appservice-discord/issues/443#issuecomment-877691120)? What is the hold up?

**Comment by samuelscheit** [comment]
I didn't contribute yet, but I will later. I would suggest to wait until I officially declare that I have time to properly maintain this project. Currently my project (Fosscord which is an open source discord compatible server and client) is heavily in development and alpha is not finished, after the first release we'll work on other messengers bridges especially on a fosscord/discord matrix bridge.

**Comment by avivace** [comment]
>  : All current maintainers gut super busy over the past few months :( 

@Sorunome @Half-Shot 

I understand you have other priorities now and I'm sorry if I'll sound too rude here but I feel like a lot of interest and traction is being wasted because of this. This is one of most discoverable tool to enable this kind of bridging, and considering the current status of many OSS projects relying on Discord (but looking for alternatives and bridges during the transition phase) this period of time is crucial to gain more userbase on Matrix, but we're still lacking a reliable tool for a smooth migration.

Not advertising the fact that you are looking for maintainers and ignoring every kind of activity here is definitely going in the opposite direction.

**Comment by jaller94** [comment]
Closing because of https://github.com/matrix-org/matrix-appservice-discord/issues/443#issuecomment-1127559316
