### ISSUE TITLE
Ability to bridge an existing matrix room to a discord channel

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#72]
Perhaps by inviting the bot, and issuing the commands to bridge a discord channel to the current room.

**Comment by Half-Shot** [comment]
Commenting about #90 in here. The long term plan is to split out provisioning into it's own handler. We'd have a provisioninghandler for the provisioning itself and then a webapi and commandhandler that feed into it. For the time being I am happy with #90 doing it inside matrixroomhandler and we can refactor later.

**Comment by Half-Shot** [comment]
Closing this as I am happy with the existing functionality.
