### ISSUE TITLE
[duplicate for #722] Discord branches/threads support

### ISSUE THREAD

**Issue by Wohlstand** [Half-Shot/matrix-appservice-discord#727]
In recent times, Discord introduced the branches (threads) feature: there are sort of sub-channels where people can separate their topics inside the same channel, avoiding the clash of multiple topics at the same channel. On the Discord side, the threads/branches are a new type of object in the protocol, so, it needs a separate implementation to handle them.

The question is, does Matrix supports similar branches thing?

P.S. Something in the protocol: https://discord.com/developers/docs/topics/threads

**Comment by Deanosim** [comment]
Currently Matrix and the Element client don't have support for threads yet, it's being worked on though.
You can see the progress here:
https://github.com/matrix-org/synapse/issues/2329
and here:
https://github.com/vector-im/element-web/issues/2349

**Comment by Wohlstand** [comment]
I see, but can that worked around for some?
two ideas:
- automatically create sub-space at the bridged space
- mix up all messages that came off threads, and the way to write into the thread from the matrix will be requirements to tag outgoing message

But right, waiting for upcoming native threads support at Matrix side, would be a wise choice, don't waste energy on a workarounds crap that will go away sooner

**Comment by sumnerevans** [comment]
See also: https://gitlab.com/beeper/issues/-/issues/2789

**Comment by Epictek** [comment]
Duplicate issue? https://github.com/Half-Shot/matrix-appservice-discord/issues/722

**Comment by Wohlstand** [comment]
Yes, you're right, it's duplicate
