### ISSUE TITLE
Images no longer bridged in either direction

### ISSUE THREAD

**Issue by lanerussell** [Half-Shot/matrix-appservice-discord#744]
Previously, images could traverse the bridge in both directions. However, this has not been working for the last few weeks. Images are not able to go from Discord -> Matrix, nor from Matrix -> Discord.

When attempting to send an image from Matrix -> Discord, a message appears as:
![Screenshot from 2021-10-28 09-34-09](https://user-images.githubusercontent.com/20979879/139278028-6e33d449-3517-4630-92f2-c19c2e47f2d1.png)

**Comment by Sinharitik589** [comment]
Can you give more info about your system and homeserver?

**Comment by lanerussell** [comment]
At some point in 5 months since this was opened, this appears to have started working again. The bridge still seems to struggle with certain MIME types, but this can be closed for now.
