### ISSUE TITLE
Plaintext messages get markdown-ified

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#75]
![image](https://user-images.githubusercontent.com/1190097/35064483-6ed03650-fb87-11e7-955b-c97c1b854250.png)

Bottom is matrix.

**Comment by Half-Shot** [comment]
Ahh, this is a message from matrix to discord? Discord do their own formatting :|

**Comment by turt2live** [comment]
Is there no escape sequence or something to avoid it?

**Comment by Half-Shot** [comment]
Ah, I missed it. You can slap a `\` in from of the message :)

**Comment by Half-Shot** [comment]
Should be fixed by 667c25e
