### ISSUE TITLE
When clicking on avatars of older messages, the wrong profile is shown

### ISSUE THREAD

**Issue by Zwelf** [Half-Shot/matrix-appservice-discord#757]
When clicking on avatars of older bridged messages in discord, a different profile picture and profile name is shown most of the times (with older = not the newest bridged message). e.g.:
![avatar_1](https://user-images.githubusercontent.com/9964758/147425604-988b9976-1eda-45e6-b0ac-fbe9ee99fe14.png)
![avatar_2](https://user-images.githubusercontent.com/9964758/147425605-ce7dc770-f1ac-43bb-a7ac-255f565823b3.png)

**Comment by D4ndellion** [comment]
this is just how webhooks on discord work

**Comment by Zwelf** [comment]
Ok, seems like nothing this bridge can do about it. If something happens, it need to be done on the discord side. Opened https://github.com/discord/discord-api-docs/issues/4280 for it
