### ISSUE TITLE
Cannot @mention Matrix users in Discord

### ISSUE THREAD

**Issue by tgr** [Half-Shot/matrix-appservice-discord#760]
While Discord mentions are correctly transformed into Matrix mentions, in Discord I can only @mention Discord users, not Matrix users. Makes sense since presence is not synced, but mentions (ie. sending notifications) are a very fundamental feature of any chat system so those not working degrades the user experience a lot. IMO some poor-man's mention support would be better than nothing - just check for any plaintext `@<matrix-nick>` string in Discord messages and convert to a mention if found.

**Comment by Zwelf** [comment]
For me this is working. Both `@<matrix-nick>` and just `<matrix-nick>` results in a ping and notification and red message highlighting. Using element-web (not sure if this is relevant). Example with `nick` the display name of the matrix user:
| discord | matrix |
| ---- | ---- |
| ![discord-mention](https://user-images.githubusercontent.com/9964758/148778419-15d39ec1-9188-44df-a255-2d4794f053b3.png) | ![matrix-mention](https://user-images.githubusercontent.com/9964758/148778423-f102f5ad-719c-4ac5-901f-665299c7f622.png) |

**Comment by tgr** [comment]
You are right about notifications since those are just simple text matches. But the nick does not get recognized. Otherwise it would look like this:
![matrix-nick-bubble](https://user-images.githubusercontent.com/145412/148848459-55f7b8a5-3e01-481e-8e5a-38e68448bfac.png)
But given that as you say this doesn't really affect notifications, maybe it doesn't matter much in practice, especially given there is no easy or elegant fix...

**Comment by Zwelf** [comment]
Yeah, I now see what you are referencing. Probably solvable for the common case, when each username is only given once. But there might not be a solution when multiple users have the same name?

**Comment by deepadmax** [comment]
It could at least parse `@username:server.tld` into `[](https://matrix.to/#/@username:server.tld)`, albeit it's more effort to enter.
