### ISSUE TITLE
Discord messages by wrong user

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#77]
IDK how to reproduce, but here's the screenshots:

Discord mobile: https://cdn.discordapp.com/attachments/237000540901474306/411260613134647296/Screenshot_20180208-134240.png

Discord web: https://img.ourl.ca/Screenshot_2018-02-08_22-04-50.png

Matrix side: https://img.ourl.ca/Screenshot_2018-02-08_21-46-16.png

**Comment by Half-Shot** [comment]
Looks like Discord mobile is having trouble switching webhooks. Slightly our fault because we utterly abuse webhooks but really it should cope with that.
