### ISSUE TITLE
You're invited to talk on Matrix

### ISSUE THREAD

**Issue by heinrich5991** [Half-Shot/matrix-appservice-discord#772]
Happens when a Matrix message mentioning Matrix users gets bridged to Discord:

![Matrix message bridged to Discord with a "You're invited to talk on Matrix" embed](https://user-images.githubusercontent.com/366230/153195011-b9fbc250-8c2c-4caf-9ec0-d0a55082fad4.png)

In native Discord messages, you can enclose links in <> to avoid the embed, like
```
thanks a lot <https://matrix.to/#/@jupeyy:matrix.org> :)
```

Does something like that work here?

**Comment by erkinalp** [comment]
On webhooks, the only option is to suppress *all* embeds with SUPPRESS_EMBEDS.

**Comment by heinrich5991** [comment]
Sounds like a good idea at least on messages only containing links for mentions.

**Comment by TurBoss** [comment]
hello, I'm unable to figure where i should set the "SUPPRESS_EMBEDS" flag

**Comment by erkinalp** [comment]
@TurBoss set 4 in the `flags` field of the Discord-side webhook.
