### ISSUE TITLE
Emotes displayed are too big

### ISSUE THREAD

**Issue by walle303** [Half-Shot/matrix-appservice-discord#79]
Emotes being inlined on matrix from discord don't have a size set, so they display as full size, often which is too large.<br>Emotes should have size tags added so that they're not awkwardly displayed.<br><br>This should be doable by adding height/width tags to the image element in the message formatted body, additionally, single-emote messages (And maybe emote-only messages with less than a certain number of emotes) should be larger than emotes within a message containing text.

**Comment by Half-Shot** [comment]
Ah, this was because I was lazy and did it via markdown rather than image tags. Hmm

**Comment by Half-Shot** [comment]
Merged. Closing.
