### ISSUE TITLE
Node.js version requirements incorrect in README.md

### ISSUE THREAD

**Issue by 0xDEADCADE** [Half-Shot/matrix-appservice-discord#817]
As seen in [this commit](https://github.com/matrix-org/matrix-appservice-discord/commit/a6bfe21b05b7fe32762fa8744700fc0cda736287#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR20), the new supported versions for Node.js are 14 to 18. [The README.md was not updated to reflect this change](https://github.com/matrix-org/matrix-appservice-discord/blob/develop/README.md#setting-up).

**Comment by Half-Shot** [comment]
Thanks for the report!
