### ISSUE TITLE
Escaping matrix event content causes problems if the text IS plain

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#82]
23adab0d9a980849d848cc0ff253f4dead2453eb introduced a regression where if the text isn't markdownable, then discord assumes the ``\`` at the start of the string is intended to be part of the message.

So a string like "\*test*" will be correctly shown as "*test*" but "\test" will show up as "\test"

Basically, Discord sucks and doesn't have a good way of escaping markdown. I'm going revert this behaviour until we can think of a good workround.

**Comment by Sorunome** [comment]
merged
