### ISSUE TITLE
Floating promises

### ISSUE THREAD

**Issue by jaller94** [Half-Shot/matrix-appservice-discord#821]
Please add `await` in front of your command or add a `.catch()` to handle possible errors.

https://github.com/matrix-org/matrix-appservice-discord/blob/57583ea03023637f1ea66414802f69a283d49a41/src/bot.ts#L221

https://github.com/matrix-org/matrix-appservice-discord/blob/57583ea03023637f1ea66414802f69a283d49a41/src/bot.ts#L1238

https://github.com/matrix-org/matrix-appservice-discord/blob/57583ea03023637f1ea66414802f69a283d49a41/src/bot.ts#L1281

We can always log a warning, but if it is 100% pointless, add `void` in front of your command to explicitly ignore the promise.

**Comment by jaller94** [comment]
Assigning you, @tadzik, because you've added or edited these lines last.

**Comment by tadzik** [comment]
I'm surprised our linter doesn't catch these, despite having `'@typescript-eslint/no-floating-promises': 'error'` in the rules – then again, we have enough errors in there, so clearly it's not enough to trigger a CI failure anyway :(
