### ISSUE TITLE
Prebuilt Docker images?

### ISSUE THREAD

**Issue by spantaleev** [Half-Shot/matrix-appservice-discord#822]
Looks like v2.0.0 is not published on Docker Hub at [halfshot/matrix-appservice-discord](https://hub.docker.com/r/halfshot/matrix-appservice-discord), or at least not yet.

[t2bot/matrix-appservice-discord](https://hub.docker.com/r/t2bot/matrix-appservice-discord) is more up-to-date, but only publishes a `:latest` tag.

Do you plan on providing up-to-date prebuilt/published Docker images or are people expected to build images themselves?

**Comment by turt2live** [comment]
Just in case: **Do not use the t2bot image in production - it is unstable and not supported for anyone other than t2bot.io**

**Comment by TheNamelessWonderer** [comment]
The docker image won't build until https://github.com/matrix-org/matrix-appservice-discord/pull/798 is merged.

**Comment by spantaleev** [comment]
That PR looks abandoned, unfortunately.

**Comment by Half-Shot** [comment]
As of today, we are now publishing against ghcr.io https://github.com/matrix-org/matrix-appservice-discord/pkgs/container/matrix-appservice-discord/33898277?tag=develop. New release is expected to land there soon!
