### ISSUE TITLE
URLs containing discord names

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#83]
If a URL contains the name of someone on discord it gets parsed to a highlight instead of a URL.

Example:

https://img.ourl.ca/Screenshot_2018-02-14_21-15-22.png

**Comment by Half-Shot** [comment]
This should have been fixed in the latest release, I've added some tests in #160

**Comment by Half-Shot** [comment]
This has been fixed.

**Comment by Sorunome** [comment]
I can confirm

Am 19. Juni 2018 13:06:45 MESZ schrieb Will Hunt <notifications@github.com>:
