### ISSUE TITLE
Messages with text and attachments that are edited lose all attachments

### ISSUE THREAD

**Issue by SethFalco** [Half-Shot/matrix-appservice-discord#859]
1. Send a message from Discord that contains both content and an attachment
2. Edit that message on Discord

The message is split into multiple messages on the Matrix side. (Which is fine.)
The attachments first, then the content.

But when the message is edited, the first associated message (the attachment) is edited and replaced with the text content of the edit and other messages remain intact.

---

Initial message from Discord, a single message that contains both content and an attachment.

![image](https://user-images.githubusercontent.com/22801583/194725673-2dcb83de-86d3-48f4-9241-d908f07343be.png)

How it appears in Matrix, 2 messages, first the attachment then the content.

![image](https://user-images.githubusercontent.com/22801583/194725688-37051b15-da5c-4401-abf8-ae1c978c812e.png)

I edit the message on the Discord side to change the content.

![image](https://user-images.githubusercontent.com/22801583/194725701-5b774033-11ae-47eb-9601-738b8258d944.png)

On Matrix, the first of the two messages is replaced with the edited content, but the attachment is lost.

![image](https://user-images.githubusercontent.com/22801583/194725710-47223ea6-5dab-4b23-80f2-f276e92671b2.png)

**Comment by erkinalp** [comment]
In Discord API 10 and newer, attachments must be re-supplied when the message is being edited.

**Comment by SethFalco** [comment]
I don't think that's the problem.

On Matrix, the message is split, the issue is just that the message with the attachment is being updated instead of the message with the text content.

At least in this particular scenario, the fix would just be to update the 2nd message instead of the 1st.

**Comment by Miepee** [comment]
I wonder if fixing #769 would fix this too.

**Comment by SethFalco** [comment]
In theory, I think it would. The fix would be incidental, but it's a valid fix imo.
If no one else looks at this, I can give it a peek next month.

**Comment by SethFalco** [comment]
Closing this, as it's adequately described in #893, and we don't need the duplicate issues.
