### ISSUE TITLE
Double Discord bot-user on Matrix side

### ISSUE THREAD

**Issue by roughnecks** [Half-Shot/matrix-appservice-discord#865]
Hello,

some time ago I set up this appservice and now I don't remember very well what I did exactly, but I think I changed nickname to the Discord Bot and now I have 2 bot-users showing up with the same nick on Matrix. Here's a picture of my userlist: https://i.imgur.com/819ryJB.jpeg

If I go to the users details, the top one (the one I think is the actual working bot) is called "@_discord_bot:woodpeckersnest.space", while the second one is called: "@_discord_1027748749549764740:woodpeckersnest.space"

What I'd like to know is if I can remove the latter from my bridged guilds in Matrix without affecting relay..

Thanks

**Comment by erkinalp** [comment]
Each user joining and leaving keeps a permanent trail in Matrix. Without that, matrix would not have worked.

**Comment by roughnecks** [comment]
I don't mind if the room keeps record of the doubled discord user joining/leaving.. I just want to be sure the relay will keep working.

**Comment by roughnecks** [comment]
Alright, removed the doubled nick from Matrix room and everything's still working fine.
