### ISSUE TITLE
replying on the discord side

### ISSUE THREAD

**Issue by Maxb0tbeep** [Half-Shot/matrix-appservice-discord#895]
is it possible to have the discord bot actually reply instead of the ugly embed? It would look a lot more seamless...

**Comment by salixor** [comment]
It is a limitation on Discord's side. Webhooks cannot reply to messages (see [!704](https://github.com/matrix-org/matrix-appservice-discord/pull/704#issuecomment-1161483468)).

**Comment by hahahahacker2009** [comment]
just implement old reply:
\> message
\@user reply message
