### ISSUE TITLE
Matrix->Discord is broken on Synapse 1.90.0+ unless use_appservice_legacy_authorization is set

### ISSUE THREAD

**Issue by jlu5** [Half-Shot/matrix-appservice-discord#896]
When I upgraded my Synapse instance today I noticed that the bridge stopped relaying from Matrix to Discord.

In the logs for matrix-appservice-discord I saw this:

```
Sep-1 06:05:15.773 [bot-sdkAppservice] info: [
  '127.0.0.1 - - [01/Sep/2023:06:05:15 +0000] "PUT /_matrix/app/v1/transactions/695537? HTTP/1.1" 401 57 "-" "Synapse/1.91.0"\n'
]
```

The workaround is to enable [`use_appservice_legacy_authorization: true`](https://matrix-org.github.io/synapse/latest/upgrade#upgrading-to-v1900) in the Synapse config, but ideally this is a temporary solution. matrix-appservice-discord should probably switch to the Authorization header mentioned in that changelog link.

**Comment by z411** [comment]
This isn't fixed for me on master. I had to use the workaround of enabling `use_appservice_legacy_authorization: true`.
