### ISSUE TITLE
trying to bridge, insufficient permissions

### ISSUE THREAD

**Issue by iraizo** [Half-Shot/matrix-appservice-discord#909]
!discord bridge 1180132841653272649 1180187893575196682
_discord_bot

ERROR: insufficient permissions to use this command! Try !discord help to see all available commands
raizo
!help
!discord help
_discord_bot

No commands found

**Comment by Mrs-Feathers** [comment]
use terminal to admin yourself. its something like "yarn adminme -m 'INTERNAL_ROOM_ID' -u '@user:yourserver.com' -p '100'"

**Comment by Mrs-Feathers** [comment]
its either that, or it only works for admins of your matrix server and you'd have to make yourself admin there, or in the config "allow !discord commands by non-admin"
