### ISSUE TITLE
Incorrect HTML escaping

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#94]
formatted_body doesn't HTML escape the parts, this is what the message source looks like

This results in some clients, like riot, not rendering the `<Sorunome>` part as it should be `&lt;Sorunome&gt;`
```
  "content": {
    "body": "**<Sorunome>** test",
    "msgtype": "m.text",
    "formatted_body": "<p><strong><Sorunome></strong> test</p>\n",
    "format": "org.matrix.custom.html"
  },
```

**Comment by Half-Shot** [comment]
Fixed by #95. Closing.
